// chinese name

#include "name.h"

mapping cn_sname = ([
        "°¢" : "a",
        "°¬" : "ai",
        "°®" : "ai",
        "°½" : "ao",
        "°×" : "bai",
        "±«" : "bao",
        "±Ï" : "bi",
        "±å" : "bian",
        "²Ì" : "cai",
        "²Ü" : "cao",
        "³Â" : "chen",
        "³þ" : "chu",
        "´÷" : "dai",
        "ñ¼" : "dou",
        "µË" : "deng",
        "µÒ" : "di",
        "¶Å" : "du",
        "¶Î" : "duan",
        "·¶" : "fan",
        "·®" : "fan",
        "·¿" : "fang",
        "·ë" : "feng",
        "·û" : "fu",
        "¸£" : "fu",
        "¸ß" : "gao",
        "¹Å" : "gu",
        "¹Ø" : "guan",
        "¹ù" : "guo",
        "º«" : "han",
        "ºú" : "hu",
        "»¨" : "hua",
        "ºé" : "hong",
        "ºî" : "hou",
        "»Æ" : "huang",
        "¼¾" : "ji",
        "¼Ö" : "jia",
        "½­" : "jiang",
        "½¯" : "jiang",
        "½ð" : "jin",
        "¿Â" : "ke",
        "¿×" : "kong",
        "¿Ü" : "kou",
        "¿ï" : "kuang",
        "ÁÎ" : "liao",
        "Áº" : "liang",
        "Àî" : "li",
        "ÁÖ" : "lin",
        "Áõ" : "liu",
        "Áú" : "long",
        "Â½" : "lu",
        "Â¬" : "lu",
        "ÂÞ" : "luo",
        "Âí" : "ma",
        "Ã«" : "mao",
        "Ã·" : "mei",
        "Ãç" : "miao",
        "Äê" : "nian",
        "Äô" : "nie",
        "Äþ" : "ning",
        "Å£" : "niu",
        "ÅË" : "pan",
        "ÅÓ" : "pang",
        "Åá" : "pei",
        "Åí" : "peng",
        "ÆÝ" : "qi",
        "Æë" : "qi",
        "Ç®" : "qian",
        "ÇÇ" : "qiao",
        "ÇØ" : "qin",
        "Çñ" : "qiu",
        "ôÃ" : "qiu",
        "³ð" : "qiu",
        "È½" : "ran",
        "ÈÎ" : "ren",
        "Èî" : "ruan",
        "É³" : "sha",
        "ÉÌ" : "shang",
        "ÉÐ" : "shang",
        "ÉÛ" : "shao",
        "Éò" : "shen",
        "Ê¦" : "shi",
        "Ê©" : "shi",
        "ËÎ" : "song",
        "Ëï" : "sun",
        "ÌÆ" : "tang",
        "ÌÕ" : "tao",
        "Ìï" : "tian",
        "Í¯" : "tong",
        "Íò" : "wan",
        "Íõ" : "wang",
        "Îº" : "wei",
        "ÎÀ" : "wei",
        "Îâ" : "wu",
        "Îä" : "wu",
        "Ï°" : "xi",
        "Ïô" : "xiao",
        "Ð¤" : "xiao",
        "Ïî" : "xiang",
        "Ðí" : "xu",
        "Ðì" : "xu",
        "Ñ¦" : "xue",
        "Ñî" : "yang",
        "Ñò" : "yang",
        "Ñô" : "yang",
        "Ò×" : "yi",
        "Òü" : "yin",
        "Óá" : "yu",
        "ÕÔ" : "zhao",
        "ÖÓ" : "zhong",
        "ÖÜ" : "zhou",
        "Ö£" : "zheng",
        "Öì" : "zhu",

        "¶«·½" : "dongfang",
        "¶À¹Â" : "dugu",
        "Ä½ÈÝ" : "murong",
        "Å·Ñô" : "ouyang",
        "Ë¾Âí" : "sima",
        "Î÷ÃÅ" : "ximen",
        "Î¾³Ù" : "yuchi",
        "³¤Ëï" : "zhangsun",
        "Öî¸ð" : "zhuge",
        "ÉÏ¹Ù" : "shangguan",
        "ÏÄºî" : "xiahou",
        "ÎÅÈË" : "wenren",
        "»Ê¸¦" : "huangfu",
        "å£Ì¨" : "tantai",
        "¹«ÖÎ" : "gongzhi",
        "´¾ÓÚ" : "chunyu",
        "ÉêÍÀ" : "shentu",
        "¹«Ëï" : "gongsun",
        "¹«Ñò" : "gongyang",
        "ÐùÔ¯" : "xuanyuan",
        "Áîºü" : "linghu",
        "ÖÓÀë" : "zhongli",
        "ÓîÎÄ" : "yuwen",
        "Ä½ÈÝ" : "murong",
        "ÖÙËï" : "zhongsun",
        "Ë¾Í½" : "situ",
        "Ë¾¿Õ" : "sikong",
        "¶ËÄ¾" : "duanmu",
        "¹«Á¼" : "gongliang",
        "°ÙÀï" : "baili",
        "¶«¹ù" : "dongguo",
        "ÏÊÓÚ" : "xianyu",
        "ÄÏ¹ù" : "nanguo",
        "ºôÑÓ" : "huyan",
        "ÑòÉà" : "yangshe",
        "¶«ÃÅ" : "dongmen",
        "ÄÉÀ¼" : "nalan",
        "ÄÏ¹Ù" : "nanguan",
        "ÄÏ¹¬" : "nangong",
        "ÍØ°Î" : "tuoba",
        "ÍêÑÕ" : "wanyan",
        "Ò®ÂÉ" : "yelv",
]);
//ÄÐÐÔNPCÃû×Ö
mapping cn_pname1 = ([
        "ai"   : "°¨°§°ª°¯°£è¨æÈÞß",
        "an"   : "°²÷öÚÏ°¶°°ÛûðÆ",
        "ao"   : "°Â°Á°½æñ°¿÷¡",
        "ang"  : "°º°»°¹",
        "ba"   : "°Õ°Ô°Ï÷É",
        "bai"  : "°×°Û",
        "ban"  : "°ß°ã",
        "bang" : "°î",
        "bei"  : "±±±¶±´±¸",
        "biao" : "±í±ê±ëì®ì­",
        "bian" : "±ß±åÛÍâí",
        "bu"   : "²½²»",
        "cao"  : "²Ü²Ý²Ùäî",
        "cang" : "²Ô²Ö",
        "chang": "³£³¤²ý³¨«`",
        "chi"  : "³Ù³Ö³Ø³à³ß³Û³ã",
        "ci"   : "´Ë´Î´Ê´Ä´Ç´È",
        "du"   : "¶À¶¼",
        "dong" : "¶«¶±",
        "dou"  : "¶¼óû",
        "fa"   : "·¢·¦·©",
        "fan"  : "·¶·²·´·º·«Þ¬",
        "fang" : "·½·ÃÚú•P",
        "feng" : "·ç·â·á·î·ã·å·æ",
        "fu"   : "·ò·û¸¥Ü½",
        "gao"  : "¸ß¸ÞÛ¬¸ä",
        "hong" : "ºéºìºêºèºçãüºë",
        "hu"   : "»¢ºöºþ»¤ºõìïä°âï",
        "hua"  : "»¯»ªæèèë",
        "hao"  : "ºÅºÆð©ÝïºÆê»å°œB",
        "ji"   : "»ý¼«¼Ã¼¼»÷¼²¼°»ù¼¯¼Ç¼Í¼¾¼Ì¼ª¼Æ¼½¼À¼Ê¼®¼¨¼É¼Åö«ð¢çáÜ¸"
                 "¼»ê«Ù¥ÆæÚµóÅçÜê÷",
        "jian" : "½¥½£¼û½¨¼ä¼í¼á¼ó",
        "kan"  : "¿¯ê¬íè",
        "ke"   : "¿É¿Ë¿Æ¿Ìçæã¡äÛ ˜",
        "lang" : "ÀÊÀËÀÈÀÅãÏÝ¹",
        "li"   : "ÀúÀëÀïÀíÀûÁ¢Á¦ÀöÀñÀèÀõÀóÁ¤èÝÁ§",
        "lin"  : "ÁÙÁØÁÖ",
        "ma"   : "Âíáï", 
        "mao"  : "Ã³Ã°Ã²Ã°í®Ã¬Ã®è£",
        "miao" : "íµÃìåã",
        "nan"  : "éªÄÏëîôö",
        "pian" : "Æ¬ôæëÝ",
        "qian" : "Ç±Ç«Ç¬ò¯Ç§",
        "qiang": "Ç¿Ç¼ïº«o",
        "qin"  : "Ç×ÇÕÇßÜËñæ",
        "qing" : "ÇåÇìÇäÇç",
        "ran"  : "È½È»È¾È¼",
        "ren"  : "ÈÊÈÐÈÉØð",
        "sha"  : "É³É·",
        "shang": "ÉÏÉÑÉÌ",
        "shen" : "ÉîÉóÉñÉêÉ÷²ÎÝ·",
        "shi"  : "Ê¦Ê·Ê¯Ê±Ê®ÊÀÊ¿Ê«Ê¼Ê¾ÊÊìÂ",
        "shui" : "Ë®",
        "si"   : "Ë¼Ë¹Ë¿Ë¾ìëËÃËÈ",
        "song" : "ËÉËÌËÐ",
        "tang" : "ÌÃÌÆÌÄè©",
        "tong" : "Í³Í¨Í¬Í¯Í®ÙÚ",
        "tian" : "ÌìÌïãÃ",
        "wan"  : "ÍòÍðÍí",
        "wei"  : "ÎÀÎ¢Î°Î¬ÍþÎ¤Î³ì¿Î©çâÎª",
        "wu"   : "ÎâÎïÎñÎäÎçÎåÎ×ÚùØ£ÎãÎì",
        "xi"   : "Î÷Ï¯ÎýÏ´Ï¦ÙâìäÏ§",
        "xiao" : "äìÏôÐ¦ÏþÐ¤ÏöæçÐ£",
        "xiong": "ÐÜÐÛ",
        "yang" : "ÑòÑóÑôÑúÑëÑíì¾ïrÑì",
        "yi"   : "Ò×ÒâÒÀÒàÒÁÒÄÒÐÒãÒåÒËÒÇÒÕÒëÒíÒÝÒäìÚÒÊÒÃÞÈÞÄÜ²ñ´éóÒÙâ¢Òî",
        "yin"  : "ÒþÒòÒýÒøÒôÒúÒ÷Ø·ÓÒñ",
        "ying" : "Ó³Ó¢Ó°Ó¦Û«Ó¥",
        "you"  : "ÓÄÓÆÓÒÓÇéàÓÏ",
        "yu"   : "ÓæÓôÔ¢ÓÚÓàÔ¤ÓðÓßÓýÓîÓíÓòÓþè¤ÓìÓùÓåØ¹ÓÝØ®Ô¥Ô£îÚìÏí²",
        "zhi"  : "ÖÆÖÁÖµÖªÖÊÖÂÖÇÖ¾Ö±ÖÎÖ´Ö¹ÖÃÖ¥Ö¼ÖÅÜÆÖ¿Û¤ÖËïôÖÄ",
        "zhong": "ÖÐÖÒÖÓÖÔ",
        "zhou" : "ÖÜÖÝÖÛëÐôíÖç",
        "zhu"  : "ÖñÖ÷×¤Öì×£ÖîÖøóÃ",
        "zhuo" : "×¿×Æ×Æ×¾×Áåªí½ßªìÌ×Ã",
        "zi"   : "×Ó×Ê×È×Îè÷",
        "zong" : "×ÚèÈ",
        "zu"   : "×ã×å×æ×ä",
        "zuo"  : "×÷×ó×ôóÐÔä",
]);

//Å®ÐÔNPCÃû×Ö
mapping cn_pname2 = ([
        "ai"   : "æÈ°®",
        "bei"  : "Ýí±´",
        "bi"   : "±Ì",
        "fang" : "·¼",
        "feng" : "·ï",
        "hong" : "ºìºç",
        "hua"  : "»¨»ª",
        "hui"  : "»Ý»ÛåçÜö",
        "ji"   : "¼§",
        "jia"  : "¼Ñ¼Î",
        "jiao" : "æ¯½¿",
        "jie"  : "½àæ¼",
        "jing" : "¾²¾§æº",
        "li"   : "ÀöÀèÀòÙ³û",
        "lian" : "ÁµÁ«",
        "lin"  : "õCÁÕ",
        "lu"   : "Â¶è´", 
        "man"  : "ÂüÂþ‹ ",
        "mei"  : "ÃÀÃ·ÃÄÝ®",
        "meng" : "ÃÎÃÈ",
        "miao" : "ÃçíµÃî",
        "qi"   : "ç÷Ší",
        "qian" : "Ù»ÜçÏË",
        "qin"  : "Ç×ÇÙÇßÜËÇÛ",
        "qing" : "ÇåÇçÇàóä",
        "sha"  : "É¯",
        "si"   : "Ë¼æ¦",
        "tong" : "Í®",
        "tian" : "Ìð",
        "ting" : "æÃ",
        "wan"  : "ÍñÝ¸ÝÒŠ€ÃäŠþ",
        "wei"  : "Þ±",
        "xi"   : "Ï¦êØ",
        "xiao" : "äìÏþ",
        "xiang": "ÏãÏæÏå",
        "xue"  : "Ñ©",
        "ya"   : "ÑÅæ«ÑÇ",
        "yan"  : "ÑÌÑàÑÞÑÕåûæÌ",
        "yang" : "ÑóÑúÑì‹PŠš",
        "yao"  : "Ò¦‹„Ñþñº",
        "yi"   : "ÒÀÒÁÒËÒÇÒÕâùÞÈÜ²",
        "yin"  : "ÒôÒ÷ÒñÒð",
        "ying" : "Ó¢Ó±çøÓ¨Ó¯Ó£Ýº",
        "yu"   : "ÓôÓñÓêÓïÓðè¤æ¥",
        "zhen" : "ÕäÕê",
        "zhi"  : "Ö¥ÜÆïôÖ¬ÖÉ",
        "zhu"  : "ÖéÜï",
        "zi"   : "×Ï×Ëïö",
]);

void generate_cn_name(object ob)
{
        string sname, pname, pname2, id1, id2;
        string *ks, *kp;
        mapping cn_pname;

        cn_pname = (ob->query("gender") == "Å®ÐÔ") ? cn_pname2 : cn_pname1;
        ks = keys(cn_sname);
        kp = keys(cn_pname);
        sname = ks[random(sizeof(ks))];
        for (;;)
        {
                pname = kp[random(sizeof(kp))];
                if (pname != cn_sname[sname]) break;
        }
        id1 = cn_sname[sname];

        id2 = pname;
        pname = cn_pname[pname];
        pname = pname[(random(sizeof(pname)) & 0xFFFE)..<1];
        pname = pname[0..1];
        if (random(3) == 0)
        {
                for (;;)
                {
                        pname2 = kp[random(sizeof(kp))];
                        if (pname2 != cn_sname[sname] &&
                            pname2 != pname) break;
                }
                id2 += pname2;
                pname2 = cn_pname[pname2];
                pname2 = pname2[(random(sizeof(pname2)) & 0xFFFE)..<1];
                pname2 = pname2[0..1];
        } else
                pname2 = "";

        if (ob) ob->set_name(sname + pname + pname2,
                             ({ id1 + " " + id2, id1, id2 }));
}

