// 普通兵器的蓝图属性；按规范 ID 自然排序。
private mapping axe_definitions() {
    return ([
        "banfu": ([
            "name": "板斧",
            "ids": ({ "axe" }),
            "weight": 6000,
            "damage": 25,
            "flags": 1,
            "properties": ({
                ({ "unit", "把" }),
                ({ "material", "steel" }),
                ({ "long", "这是一把沉重的大板斧，砍起东西来非常顺手。\n" }),
                ({ "value", 500 }),
                ({ "wield_msg", "$N拿出一把$n，握在手中当作武器。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "da_futou": ([
            "name": "大斧头",
            "ids": ({ "futou", "da futou" }),
            "weight": 7000,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一把砍柴的大斧头。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回后腰。\n" }),
            }),
        ]),
        "dabanfu": ([
            "name": "大板斧",
            "ids": ({ "bigaxe", "axe" }),
            "weight": 6000,
            "damage": 25,
            "flags": 1,
            "properties": ({
                ({ "unit", "把" }),
                ({ "material", "steel" }),
                ({ "long", "这是一把沉重的大板斧，砍起东西来非常顺手。\n" }),
                ({ "value", 1100 }),
                ({ "wield_msg", "$N拿出一把$n，握在手中当作武器。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "dabanfu2": ([
            "name": "大板斧",
            "ids": ({ "bigaxe", "axe" }),
            "weight": 6000,
            "damage": 35,
            "flags": 1,
            "properties": ({
                ({ "unit", "把" }),
                ({ "material", "steel" }),
                ({ "long", "这是一把沉重的大板斧，砍起东西来非常顺手。\n" }),
                ({ "value", 500 }),
                ({ "wield_msg", "$N拿出一把$n，握在手中当作武器。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "futou": ([
            "name": "斧头",
            "ids": ({ "axe", "fu tou" }),
            "weight": 10000,
            "damage": 30,
            "flags": 1,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把斧头，颇为沉重，是伐树的好工具。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抓起一把斧头，握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的斧头收了回来。\n" }),
            }),
        ]),
        "kanchai_fu": ([
            "name": "砍柴斧",
            "ids": ({ "fu" }),
            "weight": 5000,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄砍柴用的短斧，斧刃上有几个缺口。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "sangmen_fu": ([
            "name": "丧门斧",
            "ids": ({ "sangmen fu" }),
            "weight": 5000,
            "damage": 15,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "long", "这是一柄锋利的丧门斧。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N掣出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n反别腰后。\n" }),
            }),
        ]),
    ]);
}
