// 普通刀的蓝图属性；规范 ID 自然排序，伤害与标志由 init_blade 初始化。
private mapping blade_definitions() {
    return ([
        "bihai_jue": ([
            "name": HIG "碧海残镢" NOR,
            "ids": ({ "bihai canjue", "bihai", "blade", "dao" }),
            "weight": 4000,
            "damage": 140,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1700000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n碧海残镢乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "caidao": ([
            "name": "菜刀",
            "ids": ({ "cai dao", "blade" }),
            "weight": 7000,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的菜刀。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回裤腰。\n" }),
            }),
        ]),
        "chaidao": ([
            "name": "柴刀",
            "ids": ({ "chai dao", "dao", "cut knife", "knife" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 500 }),
                ({ "material", "iron" }),
                ({ "long", "这是一柄半新不旧的柴刀。\n" }),
                ({ "wield_msg", "$N抽出一把$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "chaidao2": ([
            "name": YEL "柴刀" NOR,
            "ids": ({ "chai dao", "chai", "dao" }),
            "weight": 500,
            "damage": 4,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", YEL "这是一柄沉甸甸的砍柴刀，普通百姓的日常用品。\n" NOR }),
                ({ "value", 10 }),
                ({ "material", "steel" }),
                ({ "wield_msg", YEL "$N" YEL "「唰」的一声抽出一柄柴刀握在手中。\n" NOR }),
                ({ "unwield_msg", YEL "$N" YEL "将手中的柴刀插回腰间。\n" NOR }),
            }),
        ]),
        "chanyi_dao": ([
            "name": CYN "蝉翼刀" NOR,
            "ids": ({ "chanyi dao", "chanyi", "blade", "dao" }),
            "weight": 4000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 250000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "chuangwang_dao": ([
            "name": "闯王宝刀",
            "ids": ({ "chuangwang baodao", "blade", "baodao" }),
            "weight": 6000,
            "damage": 150,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 500000 }),
                ({ "no_drop", 1 }),
                ({ "material", "iron" }),
                ({ "long", "这是闯王所使用过的刀，上面刻有几行小字。\n" }),
                ({ "wield_msg", "一道白光，$n已在$N手中，只觉青光四射，寒气透骨，不禁机伶伶的打个冷战。\n" }),
                ({ "unwield_msg", "$N将$n插回腰间，华光顿敛，天地间只闻龙鸣。\n" }),
            }),
        ]),
        "dadao": ([
            "name": "大刀",
            "ids": ({ "da dao", "dao" }),
            "weight": 5000,
            "damage": 10,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 1500 }),
                ({ "material", "iron" }),
                ({ "long", "这是一柄铁打的大刀。\n" }),
                ({ "wield_msg", "$N抽出一把$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "dadao2": ([
            "name": "大刀",
            "ids": ({ "da dao", "dao", "blade" }),
            "weight": 10000,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄锋利的大刀。\n" }),
                ({ "value", 1000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "dandao": ([
            "name": "单刀",
            "ids": ({ "blade" }),
            "weight": 7000,
            "damage": 20,
            "flags": 110,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的钢刀，普通官兵的常备武器。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回刀鞘。\n" }),
            }),
        ]),
        "dizang_zhan": ([
            "name": HIR "七狱地藏斩" NOR,
            "ids": ({ "dizang zhan", "dizang", "zhan", "blade", "dao" }),
            "weight": 4000,
            "damage": 230,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 4500000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七狱地藏斩乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "duan_tulong": ([
            "name": CYN "断了的屠龙刀" NOR,
            "ids": ({ "duan dao", "blade", "dao" }),
            "weight": 30000,
            "damage": 1,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄断了的刀。\n" }),
                ({ "value", 0 }),
                ({ "rigidity", 8000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "duandao": ([
            "name": "短刀",
            "ids": ({ "duan dao", "dao", "blade" }),
            "weight": 3000,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 10 }),
                ({ "long", "一柄锈迹斑斑的短刀，看样子值不了两个钱。\n" }),
                ({ "no_sell", "拿走，快拿走。这破铜烂铁值什么钱？" }),
                ({ "material", "steel" }),
            }),
        ]),
        "fenghuang_jue": ([
            "name": YEL "凤凰镢" NOR,
            "ids": ({ "fenghuang jue", "fenghuang", "jue", "blade", "dao" }),
            "weight": 4000,
            "damage": 58,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 320000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "gangdao": ([
            "name": "钢刀",
            "ids": ({ "gang dao", "gangdao", "dao", "blade" }),
            "weight": 4000,
            "damage": 25,
            "flags": 110,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 500 }),
                ({ "material", "iron" }),
                ({ "long", "这是一寻常的单刀，份量大约六、七斤重。\n" }),
                ({ "wield_msg", "$N抽出一把明晃晃的$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的刀鞘。\n" }),
            }),
        ]),
        "gangdao2": ([
            "name": HIW "钢刀" NOR,
            "ids": ({ "gang dao", "dao", "blade" }),
            "weight": 10000,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄钢铁打造的刀。\n" }),
                ({ "value", 2000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "gangdao3": ([
            "name": "钢刀",
            "ids": ({ "blade", "gangdao", "dao" }),
            "weight": 4000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 500 }),
                ({ "material", "iron" }),
                ({ "long", "这是一寻常的单刀，份量大约六、七斤重。\n" }),
                ({ "wield_msg", "$N抽出一把明晃晃的$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的刀鞘。\n" }),
            }),
        ]),
        "gangdao4": ([
            "name": "钢刀",
            "ids": ({ "blade", "dao" }),
            "weight": 7000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的钢刀，普通官兵的常备武器。\n" }),
                ({ "value", 300 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回刀鞘。\n" }),
            }),
        ]),
        "jiandao": ([
            "name": "尖刀",
            "ids": ({ "jian dao", "blade" }),
            "weight": 5000,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄杀猪刀。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "jiedao": ([
            "name": "戒刀",
            "ids": ({ "jie dao", "dao", "blade" }),
            "weight": 4000,
            "damage": 25,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 200 }),
                ({ "material", "iron" }),
                ({ "long", "这是一柄尺半长的戒刀，刀光闪闪，入手沉重，似是精铁打成。\n" }),
                ({ "wield_msg", "$N抽出一把明晃晃的$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的刀鞘。\n" }),
            }),
        ]),
        "jiedao2": ([
            "name": "戒刀",
            "ids": ({ "jie dao", "dao", "blade" }),
            "weight": 4000,
            "damage": 25,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 200 }),
                ({ "material", "iron" }),
                ({ "long", "这是一柄尺半长的戒刀，刀光闪闪，入手沉重，似是精铁打成。\n" }),
                ({ "wield_msg", "$N抽出一把明晃晃的$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的刀鞘。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "jinyang_dao": ([
            "name": HIY "金阳神刀" NOR,
            "ids": ({ "jinyang dao", "jinyang", "blade", "dao" }),
            "weight": 4000,
            "damage": 120,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1400000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "juzi": ([
            "name": YEL "锯子" NOR,
            "ids": ({ "ju zi", "ju", "zi" }),
            "weight": 500,
            "damage": 4,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", YEL "这是一用来锯木头的锯子，普通百姓的日常用品。\n" NOR }),
                ({ "value", 30 }),
                ({ "material", "steel" }),
                ({ "wield_msg", YEL "$N" YEL "拿出一把锯子握在手中。\n" NOR }),
                ({ "unwield_msg", YEL "$N" YEL "将手中的锯子抗在肩上。\n" NOR }),
            }),
        ]),
        "kandao": ([
            "name": "砍刀",
            "ids": ({ "kan dao", "dao", "blade" }),
            "weight": 7000,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄很粗笨的砍刀，大概砍柴砍竹笋还凑合。\n" }),
                ({ "value", 10 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "lengyue_dao": ([
            "name": HIG "冷月宝刀" NOR,
            "ids": ({ "moon blade", "blade" }),
            "weight": 7000,
            "damage": 180,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1000000 }),
                ({ "no_sell", "这...这玩艺怪吓人的...\n" }),
                ({ "material", "steel" }),
                ({ "long", "这是胡家祖传的宝刀，冷气森森，锐利无比。\n" }),
                ({ "wield_msg", HIG "$N" HIG "抓起刀柄，众人只觉眼前青光一"
                    "闪，寒气逼人，$N" HIG "手中已经多了一柄$n"
                    HIG "，刀光如水，流转不定。\n" NOR }),
                ({ "unwield_msg", HIW "$N" HIW "弹刀清啸，心中感慨，将$n"
                    HIW "插回刀鞘。\n" }),
            }),
        ]),
        "mandao": ([
            "name": "蛮刀",
            "ids": ({ "man dao", "dao", "blade" }),
            "weight": 7000,
            "damage": 40,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的蛮刀，是云贵少数民族首领的常备武器。\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回刀鞘。\n" }),
            }),
        ]),
        "mudao": ([
            "name": "木刀",
            "ids": ({ "mu dao", "dao", "blade" }),
            "weight": 2000,
            "damage": 5,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 500 }),
                ({ "material", "iron" }),
                ({ "long", "这是一柄木制的短刀，少林寺僧习武均用此刀，以免伤人。\n" }),
                ({ "wield_msg", "$N抽出一把$n握在手中。\n" }),
                ({ "unequip_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "mudao2": ([
            "name": "木刀",
            "ids": ({ "mu dao", "blade", "dao" }),
            "weight": 500,
            "damage": 3,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄木匠做的木刀，手工相当精细。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从腰带里抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰带上。\n" }),
            }),
        ]),
        "mutang": ([
            "name": "木镗",
            "ids": ({ "mu tang", "mu", "tang" }),
            "weight": 1500,
            "damage": 20,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "long", "这是一把作神道用的木镗。\n" }),
                ({ "wield_msg", "$N高高举起$n。\n" }),
                ({ "unwield_msg", "$N放下$n，有些气喘吁吁。\n" }),
            }),
        ]),
        "qiankun_dao1": ([
            "name": CYN "乾坤刀·乾坤" NOR,
            "ids": ({ "qian kun", "qiankundao", "blade", "dao" }),
            "weight": 4000,
            "damage": 200,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n乾坤刀·乾坤乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qiankun_dao2": ([
            "name": CYN "乾坤刀·逆乾坤" NOR,
            "ids": ({ "ni qiankun", "qiankundao", "blade", "dao" }),
            "weight": 4000,
            "damage": 210,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 4000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n乾坤刀·逆乾坤乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qing_tianyu1": ([
            "name": HIB "青天羽·七重天" NOR,
            "ids": ({ "qi chongtian", "qingtianyu", "blade", "dao" }),
            "weight": 4000,
            "damage": 150,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n青天羽·七重天乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qing_tianyu2": ([
            "name": HIB "青天羽·九重天" NOR,
            "ids": ({ "jiu chongtian", "qingtianyu", "blade", "dao" }),
            "weight": 4000,
            "damage": 160,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2500000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n青天羽·九重天乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qing_tianyu3": ([
            "name": HIB "青天羽·十二重天" NOR,
            "ids": ({ "shier chongtian", "qingtianyu", "blade", "dao" }),
            "weight": 4000,
            "damage": 170,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n青天羽·十二重天乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qingdiao_yuzhuo": ([
            "name": HIC "青雕玉琢" NOR,
            "ids": ({ "qingyu dao", "qingyu", "blade", "dao" }),
            "weight": 4000,
            "damage": 80,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1000000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "qinglong_ya": ([
            "name": HIB "青龙牙" NOR,
            "ids": ({ "qinglong ya", "qinglong", "ya", "blade", "dao" }),
            "weight": 4000,
            "damage": 70,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 580000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "qisha_ren": ([
            "name": RED "七煞阴阳刃" NOR,
            "ids": ({ "yinyang ren", "ren", "blade", "dao" }),
            "weight": 4000,
            "damage": 100,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1300000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "qiwang_dao": ([
            "name": HIY "齐王天刀" NOR,
            "ids": ({ "qiwang dao", "qiwang", "blade", "dao" }),
            "weight": 4000,
            "damage": 55,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 300000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "queyue_ren": ([
            "name": HIC "缺月刃" NOR,
            "ids": ({ "queyue ren", "queyue", "ren", "blade", "dao" }),
            "weight": 4000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 240000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "wandao": ([
            "name": "哈萨克弯刀",
            "ids": ({ "hasake wandao", "hasake", "wandao", "dao", "blade" }),
            "weight": 4000,
            "damage": 15,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的哈萨克短刀, 是哈萨克人的防身武器。\n" }),
                ({ "value", 500 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声从腰间拔出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "wodao": ([
            "name": "倭刀",
            "ids": ({ "wo dao", "blade" }),
            "weight": 7000,
            "damage": 35,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄亮晃晃的弧形弯刀，十分锋利。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回刀鞘。\n" }),
            }),
        ]),
        "wugui_ren": ([
            "name": RED "五鬼月华刃" NOR,
            "ids": ({ "wugui ren", "ren", "blade", "dao" }),
            "weight": 4000,
            "damage": 90,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1200000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "xuanjin_zhan1": ([
            "name": YEL "玄金斩·九馄阳" NOR,
            "ids": ({ "jiu hunyang", "xuanjinzhan", "blade", "dao" }),
            "weight": 4000,
            "damage": 180,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n玄金斩·九馄阳乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "xuanjin_zhan2": ([
            "name": YEL "玄金斩·披靡一阳" NOR,
            "ids": ({ "pimi yiyang", "xuanjinzhan", "blade", "dao" }),
            "weight": 4000,
            "damage": 190,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n玄金斩·披靡一阳乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "xuanjin_zhan3": ([
            "name": YEL "玄金斩·虚空" NOR,
            "ids": ({ "xu kong", "xuanjinzhan", "blade", "dao" }),
            "weight": 4000,
            "damage": 195,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3300000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n玄金斩·虚空乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "yingdao": ([
            "name": CYN "厚背鹰刀" NOR,
            "ids": ({ "ying dao", "ying", "blade", "dao" }),
            "weight": 4000,
            "damage": 65,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 340000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "yudao": ([
            "name": HIW "玉刀" NOR,
            "ids": ({ "yu dao", "yu", "dao", "blade" }),
            "weight": 500,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIW "一柄用白玉做成的单刀，相当的精美。\n" NOR }),
                ({ "value", 5000 }),
                ({ "material", "jade" }),
            }),
        ]),
        "zijin_dao": ([
            "name": MAG "紫金八卦刀" NOR,
            "ids": ({ "zijin bagua blade", "zijin blade", "bagua blade", "blade" }),
            "weight": 2000,
            "damage": 80,
            "flags": 110,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIY "这是一把金光闪闪，威猛刚劲的宝刀，刀锋中隐隐带着紫光。\n" NOR }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回刀鞘。\n" }),
            }),
        ]),
    ]);
}
