// 普通棍类物品的蓝图属性；规范 ID 自然排序，伤害与标志由 init_club 初始化。
private mapping club_definitions() {
    return ([
        "daqi": ([
            "name": HIY "大旗" NOR,
            "ids": ({ "flag", "qi" }),
            "weight": 15000,
            "damage": 10,
            "properties": ({
                ({ "unit", "面" }),
                ({ "long", "旗上绣着一头大鹰，双翅伸展，甚是威武。\n" }),
                ({ "value", 300 }),
                ({ "material", "silk" }),
                ({ "wield_msg", "$N拿出一面$n，挥舞示意。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "diaogan": ([
            "name": "钓竿",
            "ids": ({ "diao gan", "diao", "gan" }),
            "weight": 3000,
            "damage": 35,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根桦木制的钓竿，制作得颇为奇特。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "dinghai_zhen": ([
            "name": HIC "定海神针·破九域" NOR,
            "ids": ({ "po jiuyu", "club", "gun", "shenzhen" }),
            "weight": 20000,
            "damage": 220,
            "properties": ({
                ({ "unit", "支" }),
                ({ "value", 3400000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n定海神针·破九域乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，霎时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "gancheng": ([
            "name": "杆秤",
            "ids": ({ "gan cheng" }),
            "weight": 5000,
            "damage": 5,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "long", "这是一杆称量货物用的杆秤。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一杆$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "mugun": ([
            "name": "木棍",
            "ids": ({ "mu gun", "club", "gun" }),
            "weight": 500,
            "damage": 3,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "long", "这是一杆木匠做的木棍，手工相当精细。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从腰带里抽出一杆$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰带上。\n" }),
            }),
        ]),
        "panlong_gun": ([
            "name": HIY "如意盘龙棍" NOR,
            "ids": ({ "panlong gun", "gun", "panlong" }),
            "weight": 8000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 250000 }),
                ({ "material", "steel" }),
                ({ "long", "一根沉甸甸雕着盘龙的长棍。\n" }),
            }),
        ]),
        "qimei_gun": ([
            "name": "齐眉棍",
            "ids": ({ "qimei gun", "gun" }),
            "weight": 3000,
            "damage": 15,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根桦木白蜡棍，举可齐眉，轻重合宜，可攻击大片敌人。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "ruyi_gun": ([
            "name": HIW "如意棍·千钧" NOR,
            "ids": ({ "qian jun", "ruyi gun", "club", "gun" }),
            "weight": 20000,
            "damage": 160,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "value", 2400000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n如意棍·千钧乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，霎时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "shutong_gun": ([
            "name": HIY "熟铜棍" NOR,
            "ids": ({ "shutong gun", "shutong", "gun", "club" }),
            "weight": 2000,
            "damage": 60,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "long", HIY "一杆十分灵便的熟铜棍。\n" NOR }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", HIY "$N" HIY "回手从身后抽出一杆熟铜棍。\n" NOR }),
                ({ "unwield_msg", HIY "$N" HIY "手往后一扣，把熟铜棍放在身后。\n" NOR }),
            }),
        ]),
        "tianlei_dang": ([
            "name": HIR "天雷神挡" NOR,
            "ids": ({ "tianlei shendang", "tianlei", "shendang", "dang" }),
            "weight": 10000,
            "damage": 120,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "value", 1200000 }),
                ({ "material", "steel" }),
                ({ "long", "一杆上古神木所铸造的棍子，乃不世之神兵。\n" }),
                ({ "wield_msg", "$N提起$n握在手中，威风凛凛。\n" }),
            }),
        ]),
        "tiejiang": ([
            "name": "铁桨",
            "ids": ({ "tie jiang", "jiang" }),
            "weight": 3000,
            "damage": 30,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根铁桨，举可齐眉，看来很是沉重，可攻击大片敌人。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "tieqiao": ([
            "name": "铁锹",
            "ids": ({ "tie qiao", "qiao" }),
            "weight": 7000,
            "damage": 2,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一把挖矿的铁锹。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回后腰。\n" }),
            }),
        ]),
        "tongjian": ([
            "name": "熟铜锏",
            "ids": ({ "copper mace", "mace", "coppermace", "tongjian", "jian" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2000 }),
                ({ "material", "copper" }),
                ({ "long", "一柄沉甸甸的熟铜锏，上面铜锈斑斑。\n" }),
                ({ "wield_msg", "$N举起一柄$n，在地上撞出点点火星。\n" }),
                ({ "unwield_msg", "$N抹了抹$n上的锈，把它收了起来。\n" }),
            }),
        ]),
        "xuantian_gun": ([
            "name": WHT "玄天棍·鬼虐" NOR,
            "ids": ({ "gui nue", "club", "gun", "xuantian gun" }),
            "weight": 20000,
            "damage": 200,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "value", 3000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n玄天棍·鬼虐乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，霎时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
    ]);
}
