// 普通短兵器类物品的蓝图属性；规范 ID 自然排序，伤害与标志由 init_dagger 初始化。
private mapping dagger_definitions() {
    return ([
        "bajiao_shan": ([
            "name": HIG "芭蕉扇" NOR,
            "ids": ({ "bajiao shan", "bajiao", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIG "芭蕉扇蒲扇，轻便风大，价格低廉。\n" NOR }),
                ({ "value", 1000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "bishou": ([
            "name": "匕首",
            "ids": ({ "bi shou", "bishou", "dagger" }),
            "weight": 1000,
            "damage": 4,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把看起来相当普通的匕首。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从怀中摸出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n藏入怀中。\n" }),
            }),
        ]),
        "bishou2": ([
            "name": "普通匕首",
            "ids": ({ "dagger", "bishou" }),
            "weight": 6000,
            "damage": 13,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把普通的小匕首。用来暗算别人比较合适。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从兜里掏出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回兜里。\n" }),
            }),
        ]),
        "bishou3": ([
            "name": "普通匕首",
            "ids": ({ "bishou" }),
            "weight": 6000,
            "damage": 30,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把普通的小匕首。用来暗算别人比较合适。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从兜里掏出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回兜里。\n" }),
            }),
        ]),
        "chouwu_shan": ([
            "name": HIM "绸舞扇" NOR,
            "ids": ({ "chouwu shan", "chouwu", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIM "这是一把丝绸扇面，彩绘花草，舞动"
                    "时绚丽多彩的绸舞扇。\n" NOR }),
                ({ "value", 1000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "dulingzi": ([
            "name": HIB "毒绫子" NOR,
            "ids": ({ "duling dagger", "dagger", "duling" }),
            "weight": 4000,
            "damage": 140,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2500000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "fenshuici": ([
            "name": "分水刺",
            "ids": ({ "fenshui ci", "ci" }),
            "weight": 7000,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一只水中分水峨嵋刺。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一只$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回袖中。\n" }),
            }),
        ]),
        "maobi": ([
            "name": WHT "毛笔" NOR,
            "ids": ({ "mao bi", "bi", "mao" }),
            "weight": 6000,
            "damage": 15,
            "properties": ({
                ({ "unit", "支" }),
                ({ "long", "一支普通的毛笔，武林中人常常用它作为打穴的兵器。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从兜里掏出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回兜里。\n" }),
            }),
        ]),
        "panguanbi": ([
            "name": HIC "判官笔" NOR,
            "ids": ({ "panguan bi" }),
            "weight": 5000,
            "damage": 20,
            "properties": ({
                ({ "unit", "枝" }),
                ({ "long", "这是一枝精铁打就的判官笔。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N掣出一枝$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n反别腰后。\n" }),
            }),
        ]),
        "panguanbi2": ([
            "name": "镔铁判官笔",
            "ids": ({ "panguan bi", "bi", "dagger" }),
            "weight": 12000,
            "damage": 25,
            "properties": ({
                ({ "unit", "对" }),
                ({ "long", "这是一对用镔铁打造的判官笔。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声从怀中掏出一对$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n揣回怀里。\n" }),
            }),
        ]),
        "panguanbi3": ([
            "name": NOR + CYN "判官笔" NOR,
            "ids": ({ "panguan bi", "bi", "panguan" }),
            "weight": 6000,
            "damage": 40,
            "properties": ({
                ({ "unit", "支" }),
                ({ "long", "一支镔铁所铸的判官笔，武林中人常常用它作为打穴的兵器。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从兜里掏出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回兜里。\n" }),
            }),
        ]),
        "qingyang_bi": ([
            "name": HIG "青阳神匕" NOR,
            "ids": ({ "qingyang dagger", "dagger", "qingyang" }),
            "weight": 4000,
            "damage": 160,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3000000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "tanxiang_shan": ([
            "name": NOR + YEL "檀香扇" NOR,
            "ids": ({ "tanxiang shan", "tanxiang", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", NOR + YEL "这是一把由紫檀木刻制的"
                    "香木扇，芬芳馥郁。\n" NOR }),
                ({ "value", 3000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "tiegu_shan": ([
            "name": NOR + CYN "铁骨扇" NOR,
            "ids": ({ "tiegu shan", "tigu", "shan" }),
            "weight": 6000,
            "damage": 40,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", NOR + CYN "这是一把铁骨扇，武林中人常常"
                    "用它作为打穴的兵器。\n" NOR }),
                ({ "value", 3000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从兜里掏出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回兜里。\n" }),
            }),
        ]),
        "tuanshan": ([
            "name": HIC "团扇" NOR,
            "ids": ({ "tuan shan", "tuan", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIC "这是一把用上好绢丝制作的团"
                    "扇，绣着精细的花鸟。\n" NOR }),
                ({ "value", 3000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "yuban_shan": ([
            "name": HIC "玉版扇" NOR,
            "ids": ({ "yuban shan", "yuban", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIC "这是一把由苍山巨竹雕琢为扇骨，色白"
                    "润如玉，因此叫做玉版扇。\n" NOR }),
                ({ "value", 5000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "yuchang_jian": ([
            "name": WHT "鱼肠剑" NOR,
            "ids": ({ "yuchang dagger", "dagger", "yuchang" }),
            "weight": 4000,
            "damage": 100,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2000000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "yueya_bi": ([
            "name": HIC "月牙匕" NOR,
            "ids": ({ "yueya bi", "yueya", "bi", "dagger" }),
            "weight": 800,
            "damage": 35,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIC "一柄做工精细的玉制匕首。\n" NOR }),
                ({ "value", 10000 }),
                ({ "material", "stone" }),
            }),
        ]),
        "yumao_shan": ([
            "name": HIW "羽毛扇" NOR,
            "ids": ({ "yumao shan", "yumao", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIW "这是一把用雪白色的鹤翅硬翎制"
                    "作的羽毛扇。\n" NOR }),
                ({ "value", 1000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "yuxiao": ([
            "name": HIG "绿玉洞箫" NOR,
            "ids": ({ "xu xiao", "xiao" }),
            "weight": 4000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根用绿玉做成的洞箫。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声从怀中掏出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n揣回怀里。\n" }),
            }),
        ]),
        "zheshan": ([
            "name": NOR + WHT "折扇" NOR,
            "ids": ({ "zhe shan", "zhe", "shan" }),
            "weight": 200,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", NOR + WHT "这是一把做工精巧的纸面折扇。\n" NOR }),
                ({ "value", 1000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿起一把$n握在手里。\n" }),
                ({ "unwield_msg", "$N合上$n，收回怀里。\n" }),
            }),
        ]),
        "zheshan2": ([
            "name": "油纸折扇",
            "ids": ({ "zhe shan", "shan" }),
            "weight": 12000,
            "damage": 15,
            "properties": ({
                ({ "unit", "对" }),
                ({ "long", "这是一对用镔铁为骨的油纸折扇。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声从怀中掏出一只$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n揣回怀里。\n" }),
            }),
        ]),
    ]);
}
