// 直接 EQUIP 防具的蓝图属性；规范 ID 自然排序，setup 仅保留原初始化选择。
private mapping equip_definitions() {
    return ([
        "baichou_qun": ([
            "name": "白绸裙",
            "ids": ({ "baichou qun", "qun" }),
            "weight": 500,
            "properties": ({
                ({ "unit", "件" }),
                ({ "armor_type", "cloth" }),
                ({ "value", 5000 }),
                ({ "armor_prop/dodge", 5 }),
                ({ "armor_prop/armor", 2 }),
            }),
        ]),
        "baipao": ([
            "name": "白袍",
            "ids": ({ "bai pao", "pao" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "件" }),
                ({ "armor_type", "cloth" }),
                ({ "value", 200 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "armor_prop/armor", 1 }),
            }),
        ]),
        "baisiyi": ([
            "name": "白丝衣",
            "ids": ({ "bai siyi", "siyi" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "件" }),
                ({ "armor_type", "cloth" }),
                ({ "value", 2500 }),
                ({ "armor_prop/dodge", 10 }),
                ({ "armor_prop/armor", 1 }),
            }),
        ]),
        "baoshi_dai": ([
            "name": HIB "蓝宝石腰带" NOR,
            "ids": ({ "baoshi yaodai", "yaodai", "baoshi" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 3000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "waist" }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N围上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "baoshi_dai2": ([
            "name": HIB "蓝宝石腰带" NOR,
            "ids": ({ "jade belt", "belt" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 3000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "waist" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N围上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "buxie": ([
            "name": GRN "布鞋" NOR,
            "ids": ({ "bu xie", "bu", "xie" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 50 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "buxie2": ([
            "name": GRN "布鞋" NOR,
            "ids": ({ "shoes" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 50 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "danyan_sha": ([
            "name": YEL "梨芯淡烟纱" NOR,
            "ids": ({ "danyan sha", "danyan", "sha" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "danyan_sha2": ([
            "name": YEL "梨芯淡烟纱" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "guihua_shan": ([
            "name": HIW "桂花浮玉衫" NOR,
            "ids": ({ "guihua shan", "guihua", "shan" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "guihua_shan2": ([
            "name": HIW "桂花浮玉衫" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "heijin_zhuang": ([
            "name": BLK "黑色劲装" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 500 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "jiaoyue_shang": ([
            "name": HIW "琼花皎月裳" NOR,
            "ids": ({ "jiaoyue shang", "jiaoyue", "shang" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "jiaoyue_shang2": ([
            "name": HIW "琼花皎月裳" NOR,
            "ids": ({ "moon-dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "jiehun_lifu": ([
            "name": HIR "结婚礼服" NOR,
            "ids": ({ "jiehun lifu", "lifu", "jiehun" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 20000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "jiehun_lifu2": ([
            "name": HIR "结婚礼服" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 20000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 5 }),
                ({ "armor_prop/armor", 3 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "jinshen_ao": ([
            "name": BLU "彩缎紧身袄" NOR,
            "ids": ({ "jinshen ao", "jinshen", "ao" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "jinshen_ao2": ([
            "name": BLU "彩缎紧身袄" NOR,
            "ids": ({ "mini-ao" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "lihua_shang": ([
            "name": WHT "梨花飘雪裳" NOR,
            "ids": ({ "lihua shang", "lihua", "shang" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "lihua_shang2": ([
            "name": HIW "梨花飘雪裳" NOR,
            "ids": ({ "piaoxue shang", "piaoxue", "shang" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "lihua_shang3": ([
            "name": WHT "梨花飘雪裳" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "lihua_shang4": ([
            "name": HIW "梨花飘雪裳" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "magua": ([
            "name": HIC "浅蓝色马褂" NOR,
            "ids": ({ "ma gua", "ma", "gua" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 100 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "magua2": ([
            "name": HIC "浅蓝色马褂" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 100 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "nihong_qun": ([
            "name": RED "霓红连衣裙" NOR,
            "ids": ({ "nihong qun", "nihong", "qun" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "nihong_qun2": ([
            "name": RED "霓红连衣裙" NOR,
            "ids": ({ "red-dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "ningxiang_yi": ([
            "name": RED "艳露凝香衣" NOR,
            "ids": ({ "ningxiang yi", "ningxiang", "yi" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "ningxiang_yi2": ([
            "name": RED "艳露凝香衣" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "qicai_yi": ([
            "name": HIM "七彩霞云衣" NOR,
            "ids": ({ "qicai yi", "qicai", "yi" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "qicai_yi2": ([
            "name": HIM "七彩霞云衣" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "qingshan": ([
            "name": HIC "青衫" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 100 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "ruanjin_dai": ([
            "name": HIY "软金束带" NOR,
            "ids": ({ "ruanjin sudai", "sudai", "ruanjin" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "waist" }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N围上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "ruanjin_dai2": ([
            "name": HIY "软金束带" NOR,
            "ids": ({ "gold belt", "belt" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "waist" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N围上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "shaxiang_qun": ([
            "name": HIM "紫绫纱湘裙" NOR,
            "ids": ({ "shaxiang qun", "shaxiang", "qun" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "shaxiang_qun2": ([
            "name": HIM "紫绫纱湘裙" NOR,
            "ids": ({ "zi-dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "tuanjin_gua": ([
            "name": HIY "富贵团金褂" NOR,
            "ids": ({ "tuanjin gua", "tuanjin", "gua" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "tuanjin_gua2": ([
            "name": HIY "富贵团金褂" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "wucai_qun": ([
            "name": HIM "五彩绣花裙" NOR,
            "ids": ({ "wucai qun", "wucai", "qun" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "wucai_qun2": ([
            "name": HIM "五彩绣花裙" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "xiaofang_jin": ([
            "name": HIY "绣花小方巾" NOR,
            "ids": ({ "xiaofang jin", "jin", "xiaofang" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N戴上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "xiaofang_jin2": ([
            "name": HIY "绣花小方巾" NOR,
            "ids": ({ "scarf" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N戴上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "xiaoyao_jin": ([
            "name": HIB "一字逍遥巾" NOR,
            "ids": ({ "xiaoyao jin", "xiaoyao", "jin" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N戴上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "xiaoyao_jin2": ([
            "name": HIB "一字逍遥巾" NOR,
            "ids": ({ "scarf" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "条" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N戴上一条$n。\n" }),
                ({ "remove_msg", "$N将$n解了下来。\n" }),
            }),
        ]),
        "xiucai_zhuang": ([
            "name": HIM "淡烟秀才装" NOR,
            "ids": ({ "xiucai zhuang", "xiucai", "zhuang" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "xiucai_zhuang2": ([
            "name": HIM "淡烟秀才装" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "xiuhuaxie": ([
            "name": GRN "绣花鞋" NOR,
            "ids": ({ "xiuhua xie", "xiuhua", "xie" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 100 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "xiuhuaxie2": ([
            "name": GRN "绣花鞋" NOR,
            "ids": ({ "shoes" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 100 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "xiuhuaxie3": ([
            "name": "绣花鞋",
            "ids": ({ "shoes" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 0 }),
                ({ "zhongling", 1 }),
                ({ "zhong", 1 }),
                ({ "long", "这是钟灵的一双绣球鞋。\n" }),
                ({ "material", "cloth" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "xuanse_ao": ([
            "name": WHT "玄色紧身袄" NOR,
            "ids": ({ "xuanse ao", "xuanse", "ao" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "xuanse_ao2": ([
            "name": BLK "玄色紧身袄" NOR,
            "ids": ({ "cloth" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 1000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "yangpi_xue": ([
            "name": YEL "羊皮靴" NOR,
            "ids": ({ "yangpi xue", "yangpi", "xue" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 800 }),
                ({ "material", "leather" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "yangpi_xue2": ([
            "name": YEL "羊皮靴" NOR,
            "ids": ({ "boots" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "双" }),
                ({ "value", 800 }),
                ({ "material", "leather" }),
                ({ "armor_type", "feet" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 2 }),
                ({ "armor_prop/dodge", 2 }),
                ({ "wear_msg", "$N穿上一双$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "yingwu_fu": ([
            "name": HIG "翠柳鹦鹉服" NOR,
            "ids": ({ "yingwu fu", "yingwu", "fu" }),
            "weight": 700,
            "setup": 1,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "yingwu_fu2": ([
            "name": HIG "翠柳鹦鹉服" NOR,
            "ids": ({ "dress" }),
            "weight": 700,
            "properties": ({
                ({ "unit", "件" }),
                ({ "value", 2000 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "cloth" }),
                ({ "armor_prop/personality", 2 }),
                ({ "armor_prop/armor", 3 }),
                ({ "female_only", 1 }),
                ({ "wear_msg", "$N穿上一件$n。\n" }),
                ({ "remove_msg", "$将$n脱了下来。\n" }),
            }),
        ]),
        "yingzi_mao": ([
            "name": HIY "缨子帽" NOR,
            "ids": ({ "yingzi mao", "yingzi", "mao" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "unit", "顶" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N戴上一顶$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
        "yingzi_mao2": ([
            "name": HIY "缨子帽" NOR,
            "ids": ({ "hat" }),
            "weight": 1000,
            "properties": ({
                ({ "unit", "顶" }),
                ({ "value", 300 }),
                ({ "material", "cloth" }),
                ({ "armor_type", "head" }),
                ({ "armor_prop/personality", 1 }),
                ({ "armor_prop/armor", 4 }),
                ({ "armor_prop/dodge", -1 }),
                ({ "wear_msg", "$N戴上一顶$n。\n" }),
                ({ "remove_msg", "$N将$n脱了下来。\n" }),
            }),
        ]),
    ]);
}
