// 普通食物的蓝图属性；规范 ID 自然排序，行为由 ITEM + F_FOOD 提供。
private mapping food_definitions() {
    return ([
        "baicai": ([
            "name": "白菜",
            "ids": ({ "bai cai", "bai", "cai" }),
            "weight": 100,
            "properties": ({
                ({ "long", "普通的蔬菜，很新鲜，上面还滴着许许露水。\n" }),
                ({ "unit", "捆" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "baicai2": ([
            "name": HIG "大白菜" NOR,
            "ids": ({ "bai cai", "bai", "cai" }),
            "weight": 100,
            "properties": ({
                ({ "long", "新鲜的白菜。\n" }),
                ({ "unit", "棵" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "baiguo_bao": ([
            "name": HIY "百果油包" NOR,
            "ids": ({ "baozi", "dumpling" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个煎得油澄澄、香喷喷的百果油包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 70 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "baozi": ([
            "name": "包子",
            "ids": ({ "baozi", "dumpling" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的肉包子。\n" }),
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "basi_shanyao": ([
            "name": "拔丝山药",
            "ids": ({ "basi shanyao", "shanyao" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆色若玫瑰，甜嫩香嫩的拔丝山药。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "bocai_fentiao": ([
            "name": "菠菜粉条",
            "ids": ({ "bocai fentiao", "fentiao" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆白绿相间，清香可口的菠菜粉条。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "caomei": ([
            "name": "草莓",
            "ids": ({ "cao mei", "mei" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一颗鲜红的草莓。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 5 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 10 }),
            }),
        ]),
        "chayedan": ([
            "name": "五香茶叶蛋",
            "ids": ({ "spicy egg", "egg" }),
            "weight": 60,
            "properties": ({
                ({ "long", "一颗用五种香料炮制出来的茶叶蛋。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "cuyu": ([
            "name": RED "西湖醋鱼" NOR,
            "ids": ({ "fish" }),
            "weight": 1300,
            "properties": ({
                ({ "long", "一盘清甜可人的西湖醋鱼，用西湖中的金色鲤鱼
烧制而成，是西湖第一名菜。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 120 }),
                ({ "food_remaining", 20 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "dacong": ([
            "name": HIG "大葱" NOR,
            "ids": ({ "da cong", "cong", "da" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一捆新鲜的大葱。\n" }),
                ({ "unit", "捆" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "daoxiaomian": ([
            "name": "刀削面",
            "ids": ({ "daoxiao mian", "miantiao", "mian" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一碗热气腾腾的刀削面。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 200 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 35 }),
            }),
        ]),
        "dianxin": ([
            "name": "四色点心",
            "ids": ({ "gao" }),
            "weight": 1500,
            "properties": ({
                ({ "long", "四色点心形状精雅,似乎是用来玩赏一般\n" }),
                ({ "unit", "块" }),
                ({ "value", 50 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "dongporou": ([
            "name": RED "东坡肉" NOR,
            "ids": ({ "pork" }),
            "weight": 1000,
            "properties": ({
                ({ "long", "一碗香喷喷的东坡肉，用文火煨肥猪肉而成，
苏东坡在牧守杭州时看到民间吃肉而烧制不得法，遗惠此法至千年以下。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 120 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "doufu": ([
            "name": WHT "日本豆腐" NOR,
            "ids": ({ "riben doufu", "doufu" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗嫩白油滑的日本豆腐。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 25 }),
                ({ "material", "meat" }),
            }),
        ]),
        "feicui_doufu": ([
            "name": "翡翠豆腐",
            "ids": ({ "doufu", "tofu" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一块水灵灵的大豆腐，嫩的令人不禁想到阿庆嫂的脸蛋儿。\n" }),
                ({ "unit", "块" }),
                ({ "value", 40 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "feicui_gao": ([
            "name": "冰雪翡翠糕",
            "ids": ({ "gao" }),
            "weight": 1000,
            "properties": ({
                ({ "long", "这是一块糕点，引人食欲大增。\n" }),
                ({ "unit", "块" }),
                ({ "value", 50 }),
                ({ "food_remaining", 6 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "fotiaoqiang": ([
            "name": RED "佛跳墙" NOR,
            "ids": ({ "fotiaoqiang" }),
            "weight": 1000,
            "properties": ({
                ({ "long", "一碗香喷喷的佛跳墙，是福建第一名菜。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 500 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "furong_huagu": ([
            "name": "芙蓉花菇",
            "ids": ({ "furong huagu", "huagu" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆汤稠汁浓，味滑爽口的芙蓉花菇汤。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "gaoliangfan": ([
            "name": HIR "高粱米饭" NOR,
            "ids": ({ "rice", "mi fan" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗香喷喷的高粱米饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 10 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
                ({ "material", "rice" }),
            }),
        ]),
        "gourou": ([
            "name": "红烧狗肉",
            "ids": ({ "gou rou", "gou", "gourou" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一碗香喷喷的红烧狗肉\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "gourou2": ([
            "name": "红烧狗肉",
            "ids": ({ "gou rou", "gou" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一碗香喷喷的红烧狗肉\n" }),
                ({ "unit", "碗" }),
                ({ "value", 200 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "gourou3": ([
            "name": "狗肉",
            "ids": ({ "gou rou", "rou" }),
            "weight": 90,
            "properties": ({
                ({ "long", "一块香喷喷的狗肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 100 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "gourou4": ([
            "name": "狗肉",
            "ids": ({ "gou rou", "rou" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一块香喷喷的狗肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 200 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "haixian_bao": ([
            "name": "海鲜包子",
            "ids": ({ "haixian baozi", "baozi" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷、热腾腾的海鲜灌汤包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 25 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "hamigua": ([
            "name": "哈密瓜",
            "ids": ({ "hami gua", "hamigua", "gua" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一颗散发清香的哈密瓜。�n" }),
                ({ "unit", "颗" }),
                ({ "value", 120 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "hamigua2": ([
            "name": "哈密瓜",
            "ids": ({ "hamigua", "gua", "melon" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一颗香甜的哈密瓜。不吃哈密瓜等于白来西域。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 40 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "hongbing": ([
            "name": NOR + YEL "烘饼" NOR,
            "ids": ({ "hong bing", "hong", "bing" }),
            "weight": 200,
            "properties": ({
                ({ "long", YEL "这是一块香喷喷的大烘饼。\n" NOR }),
                ({ "unit", "块" }),
                ({ "value", 200 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "huangmifan": ([
            "name": YEL "黄米饭" NOR,
            "ids": ({ "rice", "mi fan" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗香喷喷的黄米饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
                ({ "material", "rice" }),
            }),
        ]),
        "huasheng": ([
            "name": "五香花生",
            "ids": ({ "huasheng", "peanut" }),
            "weight": 60,
            "properties": ({
                ({ "long", "一碟香喷喷的花生米。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 30 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "huasheng2": ([
            "name": "油炸花生",
            "ids": ({ "huasheng", "peanut" }),
            "weight": 60,
            "properties": ({
                ({ "long", "一碟香喷喷的花生米。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 30 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "huasheng3": ([
            "name": "油炸花生",
            "ids": ({ "huasheng", "peanut" }),
            "weight": 60,
            "properties": ({
                ({ "long", "一碟香喷喷的花生米。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 80 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "huluobo": ([
            "name": HIR "胡萝卜" NOR,
            "ids": ({ "hu luobo", "luobo", "hu" }),
            "weight": 100,
            "properties": ({
                ({ "long", "大红色的新鲜胡萝卜。\n" }),
                ({ "unit", "个" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "huluobo_gan": ([
            "name": "胡箩卜干",
            "ids": ({ "hu luobu", "luobu" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一块晾干了的胡箩卜干，比较方便储藏。\n" }),
                ({ "unit", "块" }),
                ({ "value", 20 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "huotui": ([
            "name": HIR "宣威火腿" NOR,
            "ids": ({ "xuanwei huotui", "huotui" }),
            "weight": 280,
            "properties": ({
                ({ "long", "这是一块用蜜饯莲子煮过，流着红油的香喷喷的宣威火腿。\n" }),
                ({ "unit", "块" }),
                ({ "value", 200 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "huotui2": ([
            "name": RED "樱桃火腿" NOR,
            "ids": ({ "yingtao huotui", "huotui" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一盆香喷喷热气腾腾的樱桃火腿。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 200 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 20 }),
                ({ "material", "meat" }),
            }),
        ]),
        "jiaohuaji": ([
            "name": "叫化鸡",
            "ids": ({ "jiaohuaji", "ji", "chicken" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一只烤得香喷喷的叫化鸡\n" }),
                ({ "unit", "只" }),
                ({ "value", 2000 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 70 }),
            }),
        ]),
        "jiaohuaji2": ([
            "name": "叫化鸡",
            "ids": ({ "jiaohua ji", "jiaohua", "ji" }),
            "weight": 200,
            "properties": ({
                ({ "long", "这是一只被烤得流油，香味扑鼻的叫化鸡。\n" }),
                ({ "unit", "只" }),
                ({ "value", 200 }),
                ({ "food_remaining", 50 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "jiaohuaji3": ([
            "name": YEL "叫化童鸡" NOR,
            "ids": ({ "chicken" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一只被烤得流油，香味扑鼻的叫化鸡。\n" }),
                ({ "unit", "只" }),
                ({ "value", 120 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "jiaxin_biqi": ([
            "name": "夹心荸荠",
            "ids": ({ "jiaxin biji", "biji" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆形态精巧别致，外脆里嫩，而又别有风味的夹心荸荠。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "juzi": ([
            "name": "桔子",
            "ids": ({ "ju zi", "juzi", "zi" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个黄橙橙的桔子。�n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "juzi2": ([
            "name": HIM "橘子" NOR,
            "ids": ({ "juzi" }),
            "weight": 100,
            "properties": ({
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "kaoya": ([
            "name": "全聚德烤鸭",
            "ids": ({ "kaoya", "ya" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一只肥得流油的全聚德烤鸭。\n" }),
                ({ "unit", "只" }),
                ({ "value", 150 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "kaoya2": ([
            "name": "烤鸭",
            "ids": ({ "kaoya", "ya" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一只肥得流油的北京烤鸭。\n" }),
                ({ "unit", "只" }),
                ({ "value", 150 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "liuli_qiezi": ([
            "name": "琉璃茄子",
            "ids": ({ "liuli qiezi", "qiezi" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆青红相间，金黄透烂，清香四溢的琉璃茄子。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "lizhi": ([
            "name": HIR "荔枝" NOR,
            "ids": ({ "lizhi" }),
            "weight": 100,
            "properties": ({
                ({ "unit", "串" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "longjing_xiaren": ([
            "name": RED "龙井虾仁" NOR,
            "ids": ({ "shrimp" }),
            "weight": 1300,
            "properties": ({
                ({ "long", "酽酽浓浓的一盘龙井虾仁。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 50 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "luobo": ([
            "name": "萝卜",
            "ids": ({ "luobo" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一支新鲜的萝卜。\n" }),
                ({ "unit", "支" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "luohan_jiyu": ([
            "name": HIY "罗汉鲫鱼" NOR,
            "ids": ({ "luohan jiyu", "jiyu", "yu" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一盘令人垂涎的" + HIY "罗汉鲫鱼" NOR + "。\n" }),
                ({ "unit", "盘" }),
                ({ "value", 1000 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mala_doufu": ([
            "name": "麻辣豆腐",
            "ids": ({ "mala doufu", "doufu" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆颜色红亮，细中带嫩，香辣可口的麻辣豆腐。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "mangguo": ([
            "name": "芒果",
            "ids": ({ "guo", "mangguo" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一颗新鲜的芒果，看了让人垂涎欲滴。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mangsherou": ([
            "name": "蟒蛇肉",
            "ids": ({ "she rou", "she" }),
            "weight": 3000,
            "properties": ({
                ({ "long", "一大块蟒蛇肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 500 }),
                ({ "food_remaining", 25 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "mantou": ([
            "name": "白面馒头",
            "ids": ({ "mantou" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一个香喷喷的白面馒头。\n" }),
                ({ "unit", "个" }),
                ({ "value", 10 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mantou2": ([
            "name": HIW "馒头" NOR,
            "ids": ({ "man tou", "man", "tou" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一个馒头。\n" }),
                ({ "unit", "个" }),
                ({ "value", 40 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 15 }),
                ({ "material", "rice" }),
            }),
        ]),
        "maoniurou": ([
            "name": "耗牛肉",
            "ids": ({ "maoniu rou", "rou" }),
            "weight": 350,
            "properties": ({
                ({ "long", "一块烧烤得香喷喷的耗牛肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 100 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 25 }),
            }),
        ]),
        "mian": ([
            "name": "面",
            "ids": ({ "mian" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一碗热气腾腾的面条。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "miantang": ([
            "name": "面汤",
            "ids": ({ "mian tang", "miantang", "mian" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一碗热气腾腾的面汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 10 }),
            }),
        ]),
        "mifan": ([
            "name": "米饭",
            "ids": ({ "rice", "mi fan", "fan" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗刚从锅里盛出来的大米饭，还冒着热气~~~~~~\n" }),
                ({ "unit", "碗" }),
                ({ "value", 120 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "mifan2": ([
            "name": "米饭",
            "ids": ({ "rice" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个碗香喷喷米饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 0 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "mifan3": ([
            "name": WHT "白米饭" NOR,
            "ids": ({ "rice", "mi fan" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗香喷喷的白米饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 10 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
                ({ "material", "rice" }),
            }),
        ]),
        "mifan4": ([
            "name": "大米饭",
            "ids": ({ "mi fan", "fan" }),
            "weight": 500,
            "properties": ({
                ({ "long", "一碗香喷喷的大米饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 30 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mitao": ([
            "name": "水蜜桃",
            "ids": ({ "tao", "mi tao" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一碟水灵新鲜的水蜜桃。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mitao2": ([
            "name": HIM "水蜜桃" NOR,
            "ids": ({ "shuimi tao", "shuimi", "tao" }),
            "weight": 40,
            "properties": ({
                ({ "long", HIM "一碟水灵新鲜的水蜜桃，跟脸蛋儿一样红艳可人。\n" NOR }),
                ({ "unit", "碟" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "mixian": ([
            "name": "过桥米线",
            "ids": ({ "guoqiao mixian", "mixian" }),
            "weight": 80,
            "properties": ({
                ({ "long", "这是一碗热气腾腾的油浸的米粉，正是大理名菜过桥米线。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "mizhi_tianou": ([
            "name": "密汁甜藕",
            "ids": ({ "mizhi tianou", "tianou" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆香甜软糯，色泽粉红的蜜汁甜藕。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "nailao": ([
            "name": "奶酪",
            "ids": ({ "nai lao", "nailao" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一块乳黄色的奶酪。\n" }),
                ({ "unit", "块" }),
                ({ "value", 150 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "nang": ([
            "name": "馕",
            "ids": ({ "nang", "cake" }),
            "weight": 80,
            "properties": ({
                ({ "long", "这是维吾尔族人日常吃的一种面饼。\n" }),
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "niaorou": ([
            "name": "鸟肉",
            "ids": ({ "niao", "bird" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一块喷香的鸟肉，真让人嘴馋。\n" }),
                ({ "unit", "块" }),
                ({ "value", 180 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "niurou": ([
            "name": "熟牛肉",
            "ids": ({ "niu rou", "rou" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一块香喷喷的熟牛肉。\n" }),
                ({ "unit", "只" }),
                ({ "value", 150 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "niurou2": ([
            "name": "红烧牛肉",
            "ids": ({ "hongshao niurou", "niurou" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盘炖得很烂很香的牛肉，看得你直流口水。\n" }),
                ({ "unit", "盘" }),
                ({ "value", 150 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "niuroumian": ([
            "name": "牛肉面",
            "ids": ({ "niurou mian", "miantiao", "mian" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一碗热气腾腾的牛肉面。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 200 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 35 }),
            }),
        ]),
        "paigumian": ([
            "name": "排骨面",
            "ids": ({ "paigu mian", "miantiao", "mian" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一碗热气腾腾的面条。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 200 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 35 }),
            }),
        ]),
        "paomo": ([
            "name": "羊肉泡馍",
            "ids": ({ "yangrou paomo", "yangrou", "paomo" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一碗香喷喷的羊肉泡馍。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 150 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "paozirou": ([
            "name": "狍子肉",
            "ids": ({ "paozi rou", "rou" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一块风干的腊肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 20 }),
                ({ "food_remaining", 15 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "pingguo": ([
            "name": "苹果",
            "ids": ({ "ping guo", "pingguo", "guo" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个大苹果。�n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "pingguo2": ([
            "name": HIG "苹果" NOR,
            "ids": ({ "pingguo" }),
            "weight": 100,
            "properties": ({
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "qiguoji": ([
            "name": "汽锅鸡",
            "ids": ({ "qiguo ji", "chicken", "ji" }),
            "weight": 280,
            "properties": ({
                ({ "long", "这是一锅热气腾腾的汽锅鸡。\n" }),
                ({ "unit", "锅" }),
                ({ "value", 200 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "qingcai": ([
            "name": HIG "大青菜" NOR,
            "ids": ({ "qing cai", "qing", "cai" }),
            "weight": 100,
            "properties": ({
                ({ "long", "新鲜的青菜。\n" }),
                ({ "unit", "棵" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "qingkemian": ([
            "name": "青稞面",
            "ids": ({ "qingke mian", "mian" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆别有风味的青稞面。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 200 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 60 }),
            }),
        ]),
        "roubao": ([
            "name": "肉包子",
            "ids": ({ "baozi", "bao" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的肉包子,不知道是用什么肉做的。\n" }),
                ({ "unit", "个" }),
                ({ "value", 20 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "ruzhu": ([
            "name": HIY "片皮乳猪" NOR,
            "ids": ({ "ruzhu" }),
            "weight": 700,
            "properties": ({
                ({ "long", "鸡豆花色白细嫩，汤清味鲜，源于豆花，高于豆花，
被誉名为“豆花不用豆，吃鸡不见鸡”的佳肴美馔。\n" }),
                ({ "unit", "只" }),
                ({ "value", 300 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "shanhu_baicai": ([
            "name": "珊瑚白菜",
            "ids": ({ "shanhu baicai", "baicai" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一盆红白相间，脆嫩爽口，清香诱人的珊瑚白菜。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "sherou": ([
            "name": "蛇肉",
            "ids": ({ "she rou", "rou" }),
            "weight": 350,
            "properties": ({
                ({ "long", "一条烧烤得香喷喷的蛇肉。\n" }),
                ({ "unit", "条" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "sherou_bao": ([
            "name": "蛇肉包子",
            "ids": ({ "baozi", "bao" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的蛇肉包子。\n" }),
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "shibing": ([
            "name": "柿饼",
            "ids": ({ "shi bing", "bing" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个好甜的柿饼。\n" }),
                ({ "unit", "个" }),
                ({ "value", 20 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "shiwu": ([
            "name": "食物",
            "ids": ({ "food" }),
            "weight": 40,
            "properties": ({
                ({ "long", "还没定义，给下层调用。\n" }),
                ({ "unit", "盘" }),
                ({ "value", 40 }),
                ({ "no_get", "1" }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 15 }),
            }),
        ]),
        "sucai_bao": ([
            "name": "素菜包子",
            "ids": ({ "sucai baozi", "baozi" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷、热腾腾的素菜灌汤包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 25 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "suji": ([
            "name": "素鸡",
            "ids": ({ "suji", "ji" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一只做工考究素鸡。\n" }),
                ({ "unit", "只" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "suya": ([
            "name": "素鸭",
            "ids": ({ "suya", "ya" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一只做工考究素鸭。\n" }),
                ({ "unit", "只" }),
                ({ "value", 150 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "tangbao": ([
            "name": "汤包",
            "ids": ({ "tangbo" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的鲜肉汤包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "tangbao2": ([
            "name": "汤包",
            "ids": ({ "tangbo" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的鲜肉汤包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "tangcu_liji": ([
            "name": RED "糖醋里脊" NOR,
            "ids": ({ "tangcu liji", "tangcu", "liji" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一份热气腾腾的糖醋里脊。\n" }),
                ({ "unit", "份" }),
                ({ "value", 160 }),
                ({ "food_remaining", 8 }),
                ({ "food_supply", 30 }),
                ({ "material", "meet" }),
            }),
        ]),
        "tanghulu": ([
            "name": HIR "冰糖葫芦" NOR,
            "ids": ({ "bingtang hulu", "bingtang", "hulu" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一串火红的冰糖葫芦\n" }),
                ({ "unit", "串" }),
                ({ "value", 50 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 10 }),
            }),
        ]),
        "tanghulu2": ([
            "name": "冰糖葫芦",
            "ids": ({ "bingtang hulu", "bingtang", "hulu" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一串火红的冰糖葫芦\n" }),
                ({ "unit", "串" }),
                ({ "value", 50 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 10 }),
            }),
        ]),
        "taohua_gao": ([
            "name": "桃花糕",
            "ids": ({ "gao" }),
            "weight": 1000,
            "properties": ({
                ({ "long", "这是一块粉红色的点心，做成了桃花状，引人食欲大增。\n" }),
                ({ "unit", "块" }),
                ({ "value", 50 }),
                ({ "food_remaining", 6 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "tudou": ([
            "name": "土豆",
            "ids": ({ "tu dou", "tu", "dou" }),
            "weight": 100,
            "properties": ({
                ({ "long", "普通的土豆。\n" }),
                ({ "unit", "个" }),
                ({ "value", 2 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "tudou_niurou": ([
            "name": HIY "土豆炖牛肉" NOR,
            "ids": ({ "potato" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗热气腾腾的土豆炖牛肉，散发出诱人的香气。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 20 }),
                ({ "food_supply", 35 }),
                ({ "material", "meat" }),
            }),
        ]),
        "tudou2": ([
            "name": "土豆",
            "ids": ({ "tu dou", "dou" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一块圆滚滚的土豆。\n" }),
                ({ "unit", "块" }),
                ({ "value", 20 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "turou": ([
            "name": "兔肉",
            "ids": ({ "tu rou", "rou" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一只烧烤得香香的兔肉。\n" }),
                ({ "unit", "只" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 25 }),
            }),
        ]),
        "turou2": ([
            "name": "兔肉",
            "ids": ({ "tu rou", "tu" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一块鲜血淋漓肥的野兔肉。\n" }),
                ({ "unit", "块" }),
                ({ "value", 200 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "xianggu": ([
            "name": YEL "清炒香菇" NOR,
            "ids": ({ "qingchao xianggu", "xianggu" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碟香喷喷的清炒香菇。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 120 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 25 }),
                ({ "material", "meat" }),
            }),
        ]),
        "xiangji": ([
            "name": RED "素暖香鸡" NOR,
            "ids": ({ "sunuan xiangji", "xiangji", "ji" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一盘令人垂涎的" + RED "素暖香鸡" NOR + "。\n" }),
                ({ "unit", "盘" }),
                ({ "value", 1000 }),
                ({ "food_remaining", 10 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "xiangjiao": ([
            "name": HIY "香蕉" NOR,
            "ids": ({ "xiangjiao" }),
            "weight": 100,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 50 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 5 }),
            }),
        ]),
        "xianli_geng": ([
            "name": HIR "桂花鲜栗羹" NOR,
            "ids": ({ "Guihua geng", "guihua", "geng" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一碗香气馥郁的桂花鲜栗羹。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 120 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "xiaomifan": ([
            "name": HIW "小米饭" NOR,
            "ids": ({ "rice" }),
            "weight": 280,
            "properties": ({
                ({ "long", HIW "一碗香喷喷的小米饭。\n" NOR }),
                ({ "unit", "碗" }),
                ({ "value", 0 }),
                ({ "food_remaining", 15 }),
                ({ "food_supply", 10 }),
            }),
        ]),
        "xiaomizhou": ([
            "name": HIW "稻香小米粥" NOR,
            "ids": ({ "rice", "fan" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗热气腾腾的小米粥。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 15 }),
                ({ "material", "rice" }),
            }),
        ]),
        "xiaren": ([
            "name": WHT "菱白虾仁" NOR,
            "ids": ({ "lingbai xiaren", "xiaren" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一盆香喷喷热气腾腾的菱白虾仁。\n" }),
                ({ "unit", "盆" }),
                ({ "value", 180 }),
                ({ "food_remaining", 8 }),
                ({ "food_supply", 20 }),
                ({ "material", "meat" }),
            }),
        ]),
        "xigua": ([
            "name": HIG "西瓜" NOR,
            "ids": ({ "xigua" }),
            "weight": 100,
            "properties": ({
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "food_remaining", 5 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "xueli": ([
            "name": "大理雪梨",
            "ids": ({ "li", "xue li" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一碟新鲜的大理雪梨。\n" }),
                ({ "unit", "碟" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "yadan": ([
            "name": "臭鸭蛋",
            "ids": ({ "chou yadan", "yadan", "egg" }),
            "weight": 70,
            "properties": ({
                ({ "long", "臭鸭蛋闻着臭，吃着香。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 80 }),
            }),
        ]),
        "yangrouchuan": ([
            "name": "羊肉串",
            "ids": ({ "yangrou chuan", "yangrou", "chuan" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一串香喷喷的羊肉串，上面沾满了孜然和辣椒面。\n" }),
                ({ "unit", "串" }),
                ({ "value", 200 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "yangtui": ([
            "name": "烤羊腿",
            "ids": ({ "kao yangtui", "yangtui", "leg" }),
            "weight": 500,
            "properties": ({
                ({ "long", "一条香喷喷的烤羊腿。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 8 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "yeerba": ([
            "name": HIG "叶儿粑" NOR,
            "ids": ({ "ye er ba", "ba" }),
            "weight": 80,
            "properties": ({
                ({ "long", "这是一块飘着清香的叶ㄦ粑。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 100 }),
                ({ "food_remaining", 15 }),
                ({ "food_supply", 20 }),
            }),
        ]),
        "yezhutui": ([
            "name": "野猪腿",
            "ids": ({ "yezhu tui", "yezhu", "tui" }),
            "weight": 200,
            "properties": ({
                ({ "long", "一块风干的腊肉。\n" }),
                ({ "unit", "条" }),
                ({ "value", 20 }),
                ({ "food_remaining", 15 }),
                ({ "food_supply", 100 }),
            }),
        ]),
        "yezi": ([
            "name": "椰子",
            "ids": ({ "ye", "yezi" }),
            "weight": 40,
            "properties": ({
                ({ "long", "一颗新鲜的椰子，看了让人垂涎欲滴。\n" }),
                ({ "unit", "颗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 30 }),
            }),
        ]),
        "yuchi": ([
            "name": "鱼翅",
            "ids": ({ "yu chi", "yu" }),
            "weight": 80,
            "properties": ({
                ({ "long", "上等鱼翅,味道鲜美.其实也就那么回事.\n" }),
                ({ "unit", "碟" }),
                ({ "value", 100 }),
                ({ "food_remaining", 1 }),
                ({ "food_supply", 1 }),
            }),
        ]),
        "zhenzhufan": ([
            "name": HIW "珍珠饭" NOR,
            "ids": ({ "rice", "fan" }),
            "weight": 0,
            "properties": ({
                ({ "long", "一碗用雪山珍珠米作的饭。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "food_remaining", 4 }),
                ({ "food_supply", 15 }),
                ({ "material", "rice" }),
            }),
        ]),
        "zhurou_bao": ([
            "name": "猪肉包子",
            "ids": ({ "zhurou baozi", "baozi" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷、热腾腾的猪肉灌汤包。\n" }),
                ({ "unit", "个" }),
                ({ "value", 25 }),
                ({ "food_remaining", 2 }),
                ({ "food_supply", 40 }),
            }),
        ]),
        "zongzi": ([
            "name": "粽子",
            "ids": ({ "zongzi" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一个香喷喷的肉粽子，包它的粽子叶泛出一股清香。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 50 }),
            }),
        ]),
        "zongzi2": ([
            "name": "粽子",
            "ids": ({ "zongzi" }),
            "weight": 80,
            "properties": ({
                ({ "long", "一个香喷喷的肉粽子，包它的粽子叶泛出一股清香。\n" }),
                ({ "unit", "个" }),
                ({ "value", 50 }),
                ({ "food_remaining", 3 }),
                ({ "food_supply", 20 }),
            }),
        ]),
    ]);
}
