// 普通锤类物品的蓝图属性；规范 ID 自然排序，伤害与标志由 init_hammer 初始化。
private mapping hammer_definitions() {
    return ([
        "chutou": ([
            "name": WHT "锄头" NOR,
            "ids": ({ "chu tou", "chu", "tou" }),
            "weight": 500,
            "damage": 4,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", WHT "这是一把锄头，普通百姓的日常务农用品。\n" NOR }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", WHT "$N" WHT "拿出一把锄头握在手中。\n" NOR }),
                ({ "unwield_msg", WHT "$N" WHT "将手中的锄头抗在肩上。\n" NOR }),
            }),
        ]),
        "datiechui": ([
            "name": "大铁锤",
            "ids": ({ "tiechui", "chui", "hammer" }),
            "weight": 5000,
            "damage": 30,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄沉重的大铁锤，后面带着长长的铁链。\n" }),
                ({ "value", 300 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「哗啷」的一声,取出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n挂回腰间。\n" }),
            }),
        ]),
        "dingyao_chui": ([
            "name": HIW "定妖神锤" NOR,
            "ids": ({ "dingyao chui", "chui", "dingyao", "hammer" }),
            "weight": 18000,
            "damage": 80,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 600000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "falun": ([
            "name": "法轮",
            "ids": ({ "fa lun", "lun", "falun" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一柄法轮，僧人们用他来作法事。\n" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回腰间。\n" }),
            }),
        ]),
        "gangchu": ([
            "name": "钢杵",
            "ids": ({ "gang chu", "gang", "chu" }),
            "weight": 5000,
            "damage": 50,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一柄全钢铸造的钢杵。\n" }),
                ({ "value", 3000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「呼」的一声抽出一柄$n高举在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n背回背上。\n" }),
                ({ "stable", 40 }),
            }),
        ]),
        "gutou": ([
            "name": "啃得精光的鸡腿骨头",
            "ids": ({ "bone" }),
            "weight": 150,
            "damage": 1,
            "properties": ({
                ({ "long", "一根啃得精光的鸡腿骨头。\n" }),
                ({ "unit", "根" }),
                ({ "wield_msg", "$N抓起一根$n，握在手中当武器。\n" }),
                ({ "material", "bone" }),
            }),
        ]),
        "hongtiechui": ([
            "name": "烧红的铁锤",
            "ids": ({ "hot hammer" }),
            "weight": 8000,
            "damage": 45,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把沈重的铁锤，打造的相当坚实。\n" }),
                ({ "value", 300 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
                ({ "stable", 0 }),
            }),
        ]),
        "jiasuo": ([
            "name": HIW "枷锁" NOR,
            "ids": ({ "jia suo", "suo", "jia" }),
            "weight": 300,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 30 }),
                ({ "material", "leather" }),
            }),
        ]),
        "jinhuoqiang": ([
            "name": HIY "金火枪" NOR,
            "ids": ({ "jin huoqiang", "jin", "huoqiang" }),
            "weight": 5000,
            "damage": 30,
            "properties": ({
                ({ "unit", "支" }),
                ({ "long", HIY "一支由黄金铸成，做工精细的火枪。\n" NOR }),
                ({ "value", 25000 }),
                ({ "wield_msg", HIY "$N摸出一支金黄色的火枪握在手中。\n" NOR }),
                ({ "unwield_msg", HIY "$N把手中的金火枪放入怀中。\n" NOR }),
            }),
        ]),
        "jinlun": ([
            "name": HIY "金轮" NOR,
            "ids": ({ "jin lun", "lun", "jinlun" }),
            "weight": 5000,
            "damage": 75,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIY "这是一柄金光闪闪的法轮。\n" NOR }),
                ({ "value", 10000 }),
                ({ "material", "gold" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回腰间。\n" }),
                ({ "stable", 50 }),
            }),
        ]),
        "kaishan_fu": ([
            "name": WHT "开山斧" NOR,
            "ids": ({ "kaishan fu", "kaishan", "fu" }),
            "weight": 5000,
            "damage": 60,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", WHT "一柄十分锋利的大斧。\n" NOR }),
                ({ "value", 100 }),
                ({ "material", "iron" }),
                ({ "wield_msg", WHT "$N" WHT "回手从身后抽出一柄大斧。\n" NOR }),
                ({ "unwield_msg", WHT "$N" WHT "手往后一别，把大斧插在后腰上。\n" NOR }),
            }),
        ]),
        "leizhen_dang": ([
            "name": WHT "雷震挡" NOR,
            "ids": ({ "leizhen dang", "leizhen", "dang" }),
            "weight": 8000,
            "damage": 60,
            "properties": ({
                ({ "unit", "杆" }),
                ({ "long", WHT "一杆十分沉重的雷震挡。\n" NOR }),
                ({ "value", 10000 }),
                ({ "material", "iron" }),
                ({ "wield_msg", WHT "$N" WHT "回手从身后抽出一杆雷震挡。\n" NOR }),
                ({ "unwield_msg", WHT "$N" WHT "手往后一扣，把雷震挡放在身后。\n" NOR }),
            }),
        ]),
        "muyu_chui": ([
            "name": "木鱼槌",
            "ids": ({ "muyu chui", "chui" }),
            "weight": 500,
            "damage": 1,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "long", "这是一把和尚念经俏木鱼用的小木槌。\n" }),
                ({ "wield_msg", "$N从衣袋里掏出一根$n，握在手中当武器。\n" }),
                ({ "unequip_msg", "$N将手中的$n放回衣袋。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "muyu_chui2": ([
            "name": "木鱼锤",
            "ids": ({ "muyu" }),
            "weight": 8000,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把很沉的铁木鱼锤\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "poyu_chui": ([
            "name": CYN "冥王破狱锤" NOR,
            "ids": ({ "mingwang chui", "mingwang", "chui", "hammer" }),
            "weight": 28000,
            "damage": 210,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 3800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n冥王破狱锤乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "qixing_chui1": ([
            "name": MAG "七星锤·镇邪" NOR,
            "ids": ({ "zhen xie", "hammer", "chui" }),
            "weight": 28000,
            "damage": 175,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 2600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星锤·镇邪乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "qixing_chui2": ([
            "name": MAG "七星锤·紫苍" NOR,
            "ids": ({ "zi cang", "hammer", "chui" }),
            "weight": 28000,
            "damage": 180,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 2800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星锤·紫苍乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "qixing_chui3": ([
            "name": MAG "七星锤·刹神" NOR,
            "ids": ({ "sha shen", "hammer", "chui" }),
            "weight": 28000,
            "damage": 200,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 3600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星锤·刹神乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" NOR }),
            }),
        ]),
        "saozhou": ([
            "name": HIY "扫帚" NOR,
            "ids": ({ "sao zhou", "sao", "zhou" }),
            "weight": 500,
            "damage": 4,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIY "这是一把扫帚，普通百姓的日常用品。\n" NOR }),
                ({ "value", 10 }),
                ({ "material", "steel" }),
                ({ "wield_msg", HIY "$N" HIY "拿出一把扫帚握在手中。\n" NOR }),
                ({ "unwield_msg", HIY "$N" HIY "将手中的扫帚抗在肩上。\n" NOR }),
            }),
        ]),
        "shigu": ([
            "name": "尸骨",
            "ids": ({ "shi gu", "shi", "gu" }),
            "weight": 200,
            "damage": 10,
            "properties": ({
                ({ "unit", "只" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "long", "这是一只白森森的尸骨。\n" }),
                ({ "wield_msg", "$N手中握住一把$n，眼中露出阴邪的笑意。\n" }),
                ({ "unwield_msg", "$N将$n插回腰间，脸色顿时也恢复了正常。\n" }),
            }),
        ]),
        "shikuai": ([
            "name": HIW "石块" NOR,
            "ids": ({ "shikuai", "stone" }),
            "weight": 5000,
            "damage": 1,
            "properties": ({
                ({ "unit", "块" }),
                ({ "long", "这是一平平常常的鹅卵石。\n" }),
                ({ "value", 0 }),
                ({ "material", "stone" }),
                ({ "wield_msg", "$N搬起一块$n准备战斗。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "shitou": ([
            "name": HIW "大石头" NOR,
            "ids": ({ "shi tou", "da shikuai", "shitou", "d" }),
            "weight": 5000,
            "damage": 1,
            "properties": ({
                ({ "unit", "块" }),
                ({ "long", "这是一平平常常的大石头。\n" }),
                ({ "value", 0 }),
                ({ "material", "stone" }),
                ({ "wield_msg", "$N搬起一块$n准备战斗。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "shitou2": ([
            "name": HIY "大石头" NOR,
            "ids": ({ "da shitou", "shitou" }),
            "weight": 2000,
            "damage": 8,
            "properties": ({
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "material", "bamboo" }),
                ({ "long", "这是一个大石头。\n" }),
                ({ "wield_msg", "$N拿出一个$n，试了试重量后握在手中。\n" }),
                ({ "unequip_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "shitou3": ([
            "name": WHT "大石头" NOR,
            "ids": ({ "stone" }),
            "weight": 16000,
            "damage": 10,
            "properties": ({
                ({ "unit", "块" }),
                ({ "long", "一块大大的圆滚滚的石头。\n" }),
                ({ "value", 0 }),
                ({ "material", "iron" }),
            }),
        ]),
        "shitou4": ([
            "name": WHT "大石头" NOR,
            "ids": ({ "stone" }),
            "weight": 5000,
            "damage": 1,
            "properties": ({
                ({ "unit", "块" }),
                ({ "long", "这是一平平常常的大石头。\n" }),
                ({ "value", 0 }),
                ({ "material", "stone" }),
                ({ "wield_msg", "$N搬起一块$n准备战斗。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "shuipiao": ([
            "name": HIG "水瓢" NOR,
            "ids": ({ "shui piao", "shui", "piao" }),
            "weight": 500,
            "damage": 4,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIG "这是一个用老葫芦劈开做成的瓢，普通百姓的日常务农用品。\n" NOR }),
                ({ "value", 10 }),
                ({ "material", "steel" }),
                ({ "wield_msg", HIG "$N" HIG "拿出一个水瓢握在手中。\n" NOR }),
                ({ "unwield_msg", HIG "$N" HIG "将手中的水瓢插在腰上。\n" NOR }),
            }),
        ]),
        "tianluo_chui": ([
            "name": HIY "天罗锤" NOR,
            "ids": ({ "tianluo chui", "chui", "tianluo", "hammer" }),
            "weight": 18000,
            "damage": 50,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 250000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "tiechui": ([
            "name": "铁锤",
            "ids": ({ "hammer" }),
            "weight": 8000,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把沈重的铁锤，打造的相当坚实。\n" }),
                ({ "value", 300 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tiechui2": ([
            "name": "铁锤",
            "ids": ({ "hammer" }),
            "weight": 8000,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把沉重的铁锤，打造的相当坚实。\n" }),
                ({ "value", 300 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然后握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tiechui3": ([
            "name": "铁锤",
            "ids": ({ "hammer" }),
            "weight": 8000,
            "damage": 15,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把沈重的铁锤，打造的相当坚实。\n" }),
                ({ "value", 3 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tiechui4": ([
            "name": "铁锤",
            "ids": ({ "hammer" }),
            "weight": 8000,
            "damage": 25,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把沈重的铁锤，打造的相当坚实。\n" }),
                ({ "value", 300 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
                ({ "stable", 0 }),
            }),
        ]),
        "tiepipa": ([
            "name": HIC "铁琵琶" NOR,
            "ids": ({ "tiepipa" }),
            "weight": 50000,
            "damage": 45,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把奇形铁琵琶，打造的相当精巧坚实。\n" }),
                ({ "value", 3 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N从背上解下一把$n，然後横在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tieqipan": ([
            "name": CYN "铁棋盘" NOR,
            "ids": ({ "tie qipan", "tie", "qipan", "pan" }),
            "weight": 10000,
            "damage": 40,
            "properties": ({
                ({ "long", CYN "一个用生铁铸成的棋盘，非常的重。\n" NOR }),
                ({ "unit", "个" }),
                ({ "value", 3000 }),
                ({ "no_sell", 1 }),
                ({ "material", "steel" }),
                ({ "stable", 80 }),
            }),
        ]),
        "tongbo": ([
            "name": YEL "铜钹" NOR,
            "ids": ({ "tong bo", "tong", "bo" }),
            "weight": 10000,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄用熟铜打造的钹。\n" }),
                ({ "value", 2000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "tongchui": ([
            "name": YEL "铜锤" NOR,
            "ids": ({ "tong chui", "tong", "chui", "hammer" }),
            "weight": 15000,
            "damage": 40,
            "properties": ({
                ({ "unit", "对" }),
                ({ "long", YEL "这是一对由青铜铸造的大锤，显得极是沉重。\n" NOR }),
                ({ "value", 3000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N振臂一挥，抡出一对沉重的$n。\n" }),
                ({ "unwield_msg", "$N将手中的$n慢慢收回。\n" }),
            }),
        ]),
        "tongren": ([
            "name": HIY "独脚铜人" NOR,
            "ids": ({ "tongren" }),
            "weight": 50000,
            "damage": 50,
            "properties": ({
                ({ "unit", "只" }),
                ({ "long", "这是一只沉重的独脚铜人，打造的相当粗大坚实。\n" }),
                ({ "value", 3 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一只$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "xigua": ([
            "name": HIG "碧绿" NOR + HIR "西瓜" NOR,
            "ids": ({ "green xigua", "xigua", "hammer" }),
            "weight": 20000,
            "damage": 80,
            "properties": ({
                ({ "unit", "对" }),
                ({ "long", "这西瓜由精钢铸成，瓜上漆成绿黑间条之色，共有一对，系以钢链。\n" }),
                ({ "value", 3000 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一对$n，试了试重量，然後握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "yaochu": ([
            "name": "药锄",
            "ids": ({ "yaochu", "chu" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把采药用的药锄，已经有些生锈了。\n" }),
                ({ "value", 100 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "yinlun": ([
            "name": HIW "银轮" NOR,
            "ids": ({ "yin lun", "lun", "yinlun" }),
            "weight": 5000,
            "damage": 50,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", HIW "这是一柄银光闪闪的法轮。\n" NOR }),
                ({ "value", 10000 }),
                ({ "material", "silver" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放回腰间。\n" }),
                ({ "stable", 40 }),
            }),
        ]),
        "yufu": ([
            "name": HIW "玉斧" NOR,
            "ids": ({ "yu fu", "yu", "fu" }),
            "weight": 500,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIW "一柄用白玉做成的斧头，相当的精美。\n" NOR }),
                ({ "value", 5000 }),
                ({ "material", "jade" }),
            }),
        ]),
    ]);
}
