// 普通饮具的固定属性及初始液体；规范 ID 自然排序，液体每次创建独立复制。
private mapping liquid_definitions() {
    return ([
        "baijiu": ([
            "name": "粗劣酒瓶",
            "ids": ({ "jiuping", "skin" }),
            "weight": 800,
            "properties": ({
                ({ "long", "一个用来装酒的酒瓶，能装两，三斤白酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "劣质白酒",
                    "remaining": 15,
                    "drunk_supply": 15,
                ]) }),
            }),
        ]),
        "beizhan": ([
            "name": "杯盏",
            "ids": ({ "water" }),
            "weight": 700,
            "properties": ({
                ({ "long", "还没定义，等下层调用。\n" }),
                ({ "unit", "杯" }),
                ({ "value", 100 }),
                ({ "no_get", "1" }),
                ({ "max_liquid", 5 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 5,
                    "supply": 10,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "biluochun": ([
            "name": "碧螺春",
            "ids": ({ "biluo chun", "cha" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "long", "这是一杯颜色碧绿、香味浓郁上等好茶。本地人称作吓煞人香。!\n" }),
                ({ "unit", "杯" }),
                ({ "value", 20 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "name": "碧螺春",
                    "remaining": 8,
                    "type": "water"
                ]) }),
                ({ "liquid_type", "water" }),
            }),
        ]),
        "caitang": ([
            "name": HIW "汤碗" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的青菜汤。\n" }),
                ({ "unit", "只" }),
                ({ "value", 10 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "菜汤",
                    "remaining": 6,
                    "drunk_supply": 30,
                ]) }),
            }),
        ]),
        "chahu": ([
            "name": "茶壶",
            "ids": ({ "tea pot", "pot" }),
            "weight": 500,
            "properties": ({
                ({ "long", "一个茶馆卖的茶壶，大概装得几升水。\n" }),
                ({ "unit", "个" }),
                ({ "value", 30 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "name": "茶水",
                    "remaining": 10,
                ]) }),
            }),
        ]),
        "cuciwan": ([
            "name": "粗磁大碗",
            "ids": ({ "wan", "da wan", "ci wan" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个蓝边粗磁大碗。\n" }),
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "cuciwan2": ([
            "name": WHT "粗磁大碗" NOR,
            "ids": ({ "wan", "dawan", "cha" }),
            "weight": 50,
            "properties": ({
                ({ "long", WHT "一个蓝边粗磁大碗。\n" NOR }),
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "dawan": ([
            "name": "海口大碗",
            "ids": ({ "wan", "bowl" }),
            "weight": 50,
            "properties": ({
                ({ "unit", "只" }),
                ({ "long", "这是一只可盛水的粗瓷大碗。\n" }),
                ({ "value", 0 }),
                ({ "max_liquid", 6 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "水",
                    "remaining": 0,
                    "drunk_apply": 0,
                ]) }),
            }),
        ]),
        "dawancha": ([
            "name": "大碗茶",
            "ids": ({ "wan", "da wan", "ci wan" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个粗磁大碗。\n" }),
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "doujiang": ([
            "name": "杯子",
            "ids": ({ "cup", "beizi" }),
            "weight": 50,
            "setup": 1,
            "properties": ({
                ({ "long", "一个磁杯子。\n" }),
                ({ "unit", "个" }),
                ({ "max_liquid", 5 }),
                ({ "liquid", ([
                    "name": "豆浆",
                    "remaining": 8,
                ]) }),
            }),
        ]),
        "gaiwancha": ([
            "name": "盖碗茶",
            "ids": ({ "gaiwan tea", "tea" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个蓝边粗磁大碗，里面盛满了茶水。\n" }),
                ({ "unit", "个" }),
                ({ "value", 2 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "gourou_tang": ([
            "name": "狗肉汤",
            "ids": ({ "gourou tang", "tang" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个满满一碗狗肉汤的大海碗，够喝一气的了。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 200 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "狗肉汤",
                    "remaining": 25,
                    "drunk_apply": 5,
                ]) }),
            }),
        ]),
        "heye_tang": ([
            "name": HIG "荷叶冬笋汤" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的荷叶冬笋汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 150 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "荷叶冬笋汤",
                    "remaining": 12,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "huacha": ([
            "name": HIY "花茶" NOR,
            "ids": ({ "tea" }),
            "weight": 700,
            "properties": ({
                ({ "long", HIY "一杯茶杯，里面盛有清香浓郁的花茶。\n" NOR }),
                ({ "unit", "杯" }),
                ({ "value", 0 }),
                ({ "max_liquid", 5 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "花茶",
                    "remaining": 5,
                    "drunk_apply": 5,
                ]) }),
            }),
        ]),
        "huadiao_dai": ([
            "name": "花雕酒袋",
            "ids": ({ "jiudai", "skin", "huadiao" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装高级花雕酒的大酒袋。\n" }),
                ({ "unit", "个" }),
                ({ "value", 120 }),
                ({ "max_liquid", 20 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "花雕酒",
                    "remaining": 20,
                    "drunk_apply": 6,
                ]) }),
            }),
        ]),
        "hulu": ([
            "name": "葫芦",
            "ids": ({ "jiouhulu", "hulu" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用葫芦制成的酒壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "百年陈酿--女儿红",
                    "remaining": 10,
                    "drunk_supply": 10,
                ]) }),
            }),
        ]),
        "hulu2": ([
            "name": "葫芦",
            "ids": ({ "hulu", "shui", "hu", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用葫芦制成的水壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 10,
                    "drunk_supply": 10,
                ]) }),
            }),
        ]),
        "jiubei": ([
            "name": "酒杯",
            "ids": ({ "wine" }),
            "weight": 700,
            "properties": ({
                ({ "long", "还没定义，等下层调用。\n" }),
                ({ "unit", "杯" }),
                ({ "value", 100 }),
                ({ "no_get", "1" }),
                ({ "max_liquid", 5 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "米酒",
                    "remaining": 5,
                    "supply": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiudai": ([
            "name": "牛皮酒袋",
            "ids": ({ "jiudai", "niupi", "skin" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装竹叶青酒的大酒袋，大概装得八、九升的酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "竹叶青酒",
                    "remaining": 15,
                    "drunk_apply": 5,
                ]) }),
            }),
        ]),
        "jiudai2": ([
            "name": "牛皮酒袋",
            "ids": ({ "jiudai", "wineskin", "skin" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装米酒的大酒袋，大概装得八、九升的酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "米酒",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiudai3": ([
            "name": "牛皮酒袋",
            "ids": ({ "jiudai", "wineskin", "skin" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装酒的大酒袋，大概装得八、九升的酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "女儿红",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiudai4": ([
            "name": "牛皮酒袋",
            "ids": ({ "jiudai", "wineskin", "skin" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装酒的大酒袋，大概装得八、九升的酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "女儿红",
                    "remaining": 30,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiudai5": ([
            "name": "牛皮酒袋",
            "ids": ({ "jiudai", "wineskin", "skin" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装米酒的大酒袋，大概装得八、九升的酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 20 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "米酒",
                    "remaining": 15,
                    "drunk_supply": 6,
                ]) }),
            }),
        ]),
        "jiuhu": ([
            "name": "酒壶",
            "ids": ({ "jiu hu", "hu", "flagon" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装烧酒的大酒壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "烧酒",
                    "remaining": 15,
                    "drunk_apply": 3,
                    "slumber_effect": 100,
                ]) }),
            }),
        ]),
        "jiuhulu": ([
            "name": "酒葫芦",
            "ids": ({ "jiouhulu", "hulu" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用葫芦制成的酒壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 200 }),
                ({ "max_liquid", 20 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "百年陈酿--女儿红",
                    "remaining": 10,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "jiuhulu2": ([
            "name": YEL "酒葫芦" NOR,
            "ids": ({ "jiu hulu", "hulu", "jiu" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装酒的大葫芦，外皮金黄，里面能装好几斤酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "米酒",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiuping": ([
            "name": GRN "酒瓶" NOR,
            "ids": ({ "jiuping", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个晶莹碧绿的的大酒瓶，装了熏熏醉人的福建老酒。\n" }),
                ({ "unit", "个" }),
                ({ "value", 200 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "福建老酒",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiuping2": ([
            "name": GRN "酒瓶" NOR,
            "ids": ({ "jiuping", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个晶莹碧绿的的大酒瓶，装了熏熏醉人的竹叶青。\n" }),
                ({ "unit", "个" }),
                ({ "value", 1600 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "竹叶青",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "jiyu_tang": ([
            "name": HIY "爆姜鲫鱼汤" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的鲫鱼汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "鲫鱼汤",
                    "remaining": 6,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "longjingcha": ([
            "name": "龙井茶",
            "ids": ({ "longjing tea", "tea" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个蓝边粗磁大碗，里面盛满了龙井茶。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 4 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "longjingcha2": ([
            "name": "一级龙井茶",
            "ids": ({ "longjing cha", "tea" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个蓝边粗磁大碗，里面盛满了龙井茶。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 20 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "manai_hu": ([
            "name": "马奶酒壶",
            "ids": ({ "hu", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装马奶酒的大酒壶，大概装得八、九升的酒。\n" }),
                ({ "unit", "只" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "马奶酒",
                    "remaining": 15,
                    "drunk_supply": 6,
                ]) }),
            }),
        ]),
        "mogu_tang": ([
            "name": MAG "汤碗" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的新鲜野菇做的汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "鲜菇汤",
                    "remaining": 6,
                    "drunk_supply": 25,
                ]) }),
            }),
        ]),
        "niupidai": ([
            "name": "牛皮袋",
            "ids": ({ "niu pidai", "pidai", "dai", "skin" }),
            "weight": 200,
            "properties": ({
                ({ "long", "这是用来装酥油茶的牛皮袋，散发出淡淡的乳香。\n" }),
                ({ "unit", "个" }),
                ({ "value", 150 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "suyou cha",
                    "name": "酥油茶",
                    "remaining": 10,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "nverhong": ([
            "name": "女儿红",
            "ids": ({ "nver hong", "wine" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一坛上好的女儿红,醇香诱人.\n" }),
                ({ "unit", "坛" }),
                ({ "value", 500 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "女儿红酒",
                    "remaining": 3,
                    "drunk_supply": 6,
                ]) }),
            }),
        ]),
        "puercha": ([
            "name": "茶壶",
            "ids": ({ "chahu", "hu", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用来装茶的大茶壶，大概装得八、九杯的茶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 150 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "云南普洱茶",
                    "remaining": 15,
                    "drunk_apply": 5,
                ]) }),
            }),
        ]),
        "qing_hulu": ([
            "name": HIG "青葫芦" NOR,
            "ids": ({ "qing hulu", "hulu" }),
            "weight": 400,
            "properties": ({
                ({ "long", "这是一个碧绿色的葫芦。\n" }),
                ({ "unit", "个" }),
                ({ "value", 80 }),
                ({ "max_liquid", 30 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "甘泉水",
                    "remaining": 40,
                ]) }),
            }),
        ]),
        "qinghua_wan": ([
            "name": "缺口的青花瓷碗",
            "ids": ({ "qinghua ciwan", "wan", "ciwan" }),
            "weight": 100,
            "properties": ({
                ({ "long", "一个缺了口的粗瓷碗。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "清水",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "qingshui": ([
            "name": HIY "清水" NOR,
            "ids": ({ "water", "shui" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗清水。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 10 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 6,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "qingshui_hulu": ([
            "name": "清水葫芦",
            "ids": ({ "qingshui hulu", "hulu", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个用葫芦制成的水壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 10,
                    "drunk_supply": 10,
                ]) }),
            }),
        ]),
        "shuihu": ([
            "name": "水壶",
            "ids": ({ "water bottle", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个不知道用什么动物的皮制成的水壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 10,

                ]) }),
            }),
        ]),
        "shuihu2": ([
            "name": "水壶",
            "ids": ({ "water bottle", "bottle" }),
            "weight": 700,
            "properties": ({
                ({ "long", "一个不知道用什么动物的皮制成的水壶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 100 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "清水",
                    "remaining": 10,
                    "drunk_supply": 5,
                ]) }),
            }),
        ]),
        "shuiwan": ([
            "name": "水碗",
            "ids": ({ "wan", "bowl" }),
            "weight": 400,
            "properties": ({
                ({ "long", "这是一个水碗，里面有什么呢？当然是水啦。\n" }),
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "水",
                    "remaining": 10,
                ]) }),
            }),
        ]),
        "shuiwan2": ([
            "name": "水碗",
            "ids": ({ "wan", "bowl" }),
            "weight": 400,
            "properties": ({
                ({ "long", "这是一个水碗，里面有什么呢？当然是水啦。\n" }),
                ({ "unit", "个" }),
                ({ "value", 0 }),
                ({ "max_liquid", 60 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "水",
                    "remaining": 60,
                ]) }),
            }),
        ]),
        "suancai_tang": ([
            "name": GRN "酸菜粉丝汤" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的酸菜粉丝汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 160 }),
                ({ "max_liquid", 8 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "酸菜粉丝汤",
                    "remaining": 12,
                    "drunk_supply": 40,
                ]) }),
            }),
        ]),
        "suanmei_tang": ([
            "name": "酸梅汤",
            "ids": ({ "suanmei tang", "tang" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "long", "这是一碗解渴良汤。!\n" }),
                ({ "unit", "碗" }),
                ({ "value", 20 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "name": "酸梅汤",
                    "remaining": 8,
                    "type": "water"
                ]) }),
                ({ "liquid_type", "water" }),
            }),
        ]),
        "wulongcha": ([
            "name": "乌龙茶",
            "ids": ({ "wulong tea", "tea" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一个蓝边粗磁大碗，里面盛满了乌龙茶。\n" }),
                ({ "unit", "个" }),
                ({ "value", 4 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "tea",
                    "name": "茶水",
                    "remaining": 4,
                    "drunk_supply": 0,
                ]) }),
            }),
        ]),
        "xiangcha": ([
            "name": GRN "香茶" NOR,
            "ids": ({ "tea" }),
            "weight": 30,
            "properties": ({
                ({ "long", "一杯香茶。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 10 }),
                ({ "max_liquid", 20 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "香茶",
                    "remaining": 20,
                    "drunk_supply": 40,
                ]) }),
            }),
        ]),
        "xuehe_tang": ([
            "name": HIC "雪鹤汤" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗香气扑鼻的雪鹤汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 80 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "雪鹤汤",
                    "remaining": 6,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "yecai_tang": ([
            "name": HIG "野菜汤碗" NOR,
            "ids": ({ "soup" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗新鲜野菜做的汤。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 10 }),
                ({ "max_liquid", 4 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "野菜汤",
                    "remaining": 6,
                    "drunk_supply": 20,
                ]) }),
            }),
        ]),
        "zaopen": ([
            "name": "木澡盆",
            "ids": ({ "zaopen" }),
            "weight": 500000,
            "properties": ({
                ({ "long", "木头的澡盆,已经很陈旧。\n" }),
                ({ "unit", "只" }),
                ({ "value", 100 }),
                ({ "max_liquid", 15 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": "洗澡水",
                    "remaining": 15,
                    "drunk_apply": 3,
                ]) }),
            }),
        ]),
        "zhou": ([
            "name": GRN "粗瓷碗" NOR,
            "ids": ({ "wan" }),
            "weight": 50,
            "properties": ({
                ({ "long", "一碗热气腾腾的粥。\n" }),
                ({ "unit", "碗" }),
                ({ "value", 20 }),
                ({ "max_liquid", 20 }),
                ({ "liquid", ([
                    "type": "water",
                    "name": "热粥",
                    "remaining": 20,
                    "drunk_supply": 40,
                ]) }),
            }),
        ]),
        "zuixiancha": ([
            "name": "醉仙茶",
            "ids": ({ "zuixian cha", "cha" }),
            "weight": 1000,
            "setup": 1,
            "properties": ({
                ({ "long", "这是一杯颜色碧绿、香味浓郁上等好茶。是招待桃花岛来客的。!\n" }),
                ({ "unit", "杯" }),
                ({ "value", 20 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "name": "醉仙茶",
                    "remaining": 8,
                    "type": "water"
                ]) }),
                ({ "liquid_type", "water" }),
            }),
        ]),
        "zuixunfeng": ([
            "name": MAG "醉熏风" NOR,
            "ids": ({ "zui xunfeng", "xunfeng" }),
            "weight": 300,
            "properties": ({
                ({ "long", "一壶巴蜀佳酿" MAG + "醉熏风" NOR "，甜美醇绵。\n" }),
                ({ "unit", "壶" }),
                ({ "value", 500 }),
                ({ "max_liquid", 10 }),
                ({ "liquid", ([
                    "type": "alcohol",
                    "name": MAG "醉熏风" NOR "佳酿",
                    "remaining": 25,
                    "drunk_apply": 7,
                ]) }),
            }),
        ]),
    ]);
}
