// 普通杖类物品的蓝图属性；规范 ID 自然排序，伤害与标志由 init_staff 初始化。
private mapping staff_definitions() {
    return ([
        "baxian_zhang": ([
            "name": HIR "八仙杖" NOR,
            "ids": ({ "baxian zhang", "zhang", "baxian", "staff" }),
            "weight": 13000,
            "damage": 100,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1400000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "biandan": ([
            "name": "熟铁扁担",
            "ids": ({ "bian dan" }),
            "weight": 50000,
            "damage": 15,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "通身黑油油地，中间微弯，两头各有一个突起的鞘子。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "chaihe": ([
            "name": "柴禾",
            "ids": ({ "chai he", "staff" }),
            "weight": 2000,
            "damage": 5,
            "properties": ({
                ({ "unit", "根" }),
                ({ "material", "wood" }),
                ({ "long", "这是一根粗长的树枝。\n" }),
            }),
        ]),
        "chanzhang": ([
            "name": "禅杖",
            "ids": ({ "staff", "zhang" }),
            "weight": 4000,
            "damage": 25,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把禅杖，上面几个铁环叮当作响．\n" }),
                ({ "value", 500 }),
                ({ "material", "iron" }),
                ({ "wield_msg", "$N拿出一把$n，握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "chanzhang2": ([
            "name": "禅杖",
            "ids": ({ "chan zhang", "zhang" }),
            "weight": 6000,
            "damage": 25,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根黑黝黝的镔铁禅杖，约四十来斤，是件称手的重兵器。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "chuihuo_guan": ([
            "name": "吹火管",
            "ids": ({ "chui huoguan", "guan" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 10 }),
                ({ "long", "在一端吹气,使灶火旺盛的竹管.\n" }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N「呼」地一声抽出一把$n握在手中。\n" }),
            }),
        ]),
        "gangzhang": ([
            "name": "钢杖",
            "ids": ({ "gangzhang" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根粗重的钢杖。\n" }),
                ({ "value", 200 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "gangzhang2": ([
            "name": "钢杖",
            "ids": ({ "gangzhang" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根粗重的钢杖，是星宿派专用之物。\n" }),
                ({ "value", 1500 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "huoqiang": ([
            "name": "荷兰火枪",
            "ids": ({ "helan huoqiang", "huoqiang" }),
            "weight": 5000,
            "damage": 30,
            "properties": ({
                ({ "unit", "支" }),
                ({ "long", "一支荷兰火枪。可惜只能放一枪。\n" }),
                ({ "value", 10000 }),
                ({ "material", "bamboo" }),
                ({ "wield_msg", "$N抽出一支乌油的木柄火枪握在手中。\n" }),
                ({ "unwield_msg", "$N把手中的火枪背回背上。\n" }),
            }),
        ]),
        "jingtie_zhang": ([
            "name": WHT "精铁杖" NOR,
            "ids": ({ "tie zhang", "tie", "zhang" }),
            "weight": 20000,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄用镔铁打造的杖。\n" }),
                ({ "value", 2000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "jiuhuang_zhang": ([
            "name": HIY "九凰杖" NOR,
            "ids": ({ "jiuhuang zhang", "zhang", "jiuhuang", "staff" }),
            "weight": 13000,
            "damage": 65,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 450000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "kusang_bang": ([
            "name": "哭丧棒",
            "ids": ({ "kusang bang", "kusang", "bang" }),
            "weight": 2000,
            "damage": 35,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根精铁打铸的哭丧棒。\n" }),
                ({ "value", 800 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "langyabang": ([
            "name": "狼牙棒",
            "ids": ({ "langya bang", "bang" }),
            "weight": 30000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根两头狼牙棒，约两百来斤，是件称手的重兵器。\n" }),
                ({ "value", 2000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "laojun_zhang": ([
            "name": RED "老君绝灭杖·三味火" NOR,
            "ids": ({ "sanwei huo", "laojunzhang", "zhang", "staff" }),
            "weight": 22000,
            "damage": 220,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 4000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n老君绝灭杖·三味火乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直聂九霄。\n" NOR }),
            }),
        ]),
        "mugun": ([
            "name": "木棍",
            "ids": ({ "mu gun", "gun" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根木棍，举可齐眉，轻重合宜，可攻击大片敌人。\n" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "muzhang": ([
            "name": "木杖",
            "ids": ({ "mu zhang" }),
            "weight": 1000,
            "damage": 60,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根龙头木杖。\n" }),
                ({ "value", 200 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n矗立在地上。\n" }),
            }),
        ]),
        "panlong_zhang": ([
            "name": HIR "盘龙杖" NOR,
            "ids": ({ "panlong zhang", "zhang", "panlong", "staff" }),
            "weight": 8000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 250000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "qixing_zhang1": ([
            "name": MAG "七星杖·轮回" NOR,
            "ids": ({ "lun hui", "qixingzhang", "zhang", "staff" }),
            "weight": 18000,
            "damage": 120,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星杖·轮回乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直聂九霄。\n" NOR }),
            }),
        ]),
        "qixing_zhang2": ([
            "name": MAG "七星杖·诛天" NOR,
            "ids": ({ "zhu tian", "qixingzhang", "zhang", "staff" }),
            "weight": 18000,
            "damage": 150,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星杖·诛天乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直聂九霄。\n" NOR }),
            }),
        ]),
        "qixing_zhang3": ([
            "name": MAG "七星杖·寂灭" NOR,
            "ids": ({ "ji mie", "qixingzhang", "zhang", "staff" }),
            "weight": 22000,
            "damage": 150,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 2600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星杖·寂灭乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直聂九霄。\n" NOR }),
            }),
        ]),
        "qixing_zhang4": ([
            "name": RED "七星杖·麒麟火" NOR,
            "ids": ({ "qilin huo", "qixingzhang", "zhang", "staff" }),
            "weight": 22000,
            "damage": 180,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 3200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n七星杖·麒麟火乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直聂九霄。\n" NOR }),
            }),
        ]),
        "senggun": ([
            "name": "僧棍",
            "ids": ({ "seng gun", "gun" }),
            "weight": 3000,
            "damage": 15,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根桦木白腊棍，举可齐眉，轻重合宜，可攻击大片敌人。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
                ({ "shaolin", 1 }),
            }),
        ]),
        "shawei_bang": ([
            "name": "杀威棒",
            "ids": ({ "shawei bang", "bang" }),
            "weight": 3000,
            "damage": 20,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 200 }),
                ({ "material", "wood" }),
            }),
        ]),
        "shouzhang": ([
            "name": "手杖",
            "ids": ({ "walking stick", "stick" }),
            "weight": 1000,
            "damage": 5,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根爬山用的手杖。\n" }),
                ({ "value", 100 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N拿出一根$n，握在手中。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tianya_guai": ([
            "name": HIG "天涯拐" NOR,
            "ids": ({ "tianya guai", "guai", "tianya", "staff" }),
            "weight": 13000,
            "damage": 80,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 900000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "tie_lingpai": ([
            "name": "铁灵牌",
            "ids": ({ "tie lingpai", "tie", "lingpai" }),
            "weight": 2000,
            "damage": 35,
            "properties": ({
                ({ "unit", "副" }),
                ({ "long", "这是一副精铁打铸的铁灵牌。\n" }),
                ({ "value", 800 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一副$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "tiebian": ([
            "name": "铁鞭",
            "ids": ({ "tie bian", "tie", "bian" }),
            "weight": 500,
            "damage": 40,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄粗大的铁鞭，总有三十来斤重。\n" }),
                ({ "value", 100 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n别回腰间。\n" }),
            }),
        ]),
        "tiejiang": ([
            "name": WHT "铁桨" NOR,
            "ids": ({ "tie jiang", "tie", "jiang" }),
            "weight": 3000,
            "damage": 30,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根铁桨，举可齐眉，看来很是沉重，可攻击大片敌人。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "zhaohun_fan": ([
            "name": "招魂幡",
            "ids": ({ "zhaohun fan", "zhaohun", "fan" }),
            "weight": 2000,
            "damage": 35,
            "properties": ({
                ({ "unit", "面" }),
                ({ "long", "这是一面精铁打铸的招魂幡。\n" }),
                ({ "value", 800 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一面$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "zhubang": ([
            "name": "竹棒",
            "ids": ({ "zhubang" }),
            "weight": 3000,
            "damage": 10,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根发黄的竹棒，入手沉甸甸的，似乎相当结实。\n" }),
                ({ "value", 200 }),
                ({ "material", "bamboo" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "zhubang2": ([
            "name": "竹棒",
            "ids": ({ "zhubang" }),
            "weight": 3000,
            "damage": 25,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根发黄的竹棒，入手沉甸甸的，似乎相当结实。\n" }),
                ({ "value", 200 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "zhubang3": ([
            "name": NOR + GRN "竹棒" NOR,
            "ids": ({ "zhu bang", "zhu", "bang" }),
            "weight": 1500,
            "damage": 5,
            "properties": ({
                ({ "long", GRN "这是一根颇为破旧的竹棒，可以作为手杖使用。\n" NOR }),
                ({ "unit", "根" }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
    ]);
}
