// 普通剑的蓝图属性；规范 ID 自然排序，伤害由 init_sword 初始化。
private mapping sword_definitions() {
    return ([
        "baihong_jian": ([
            "name": "白虹剑",
            "ids": ({ "baihongjian", "sword", "jian" }),
            "weight": 8000,
            "damage": 90,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一口削铁如泥的宝剑。\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "weapon_prop/personality", 8 }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄寒光闪闪的$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "bintie_jian": ([
            "name": CYN "镔铁长剑" NOR,
            "ids": ({ "chang jian", "sword", "jian" }),
            "weight": 10000,
            "damage": 15,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄锋利的长剑。\n" }),
                ({ "value", 1200 }),
                ({ "material", "gold" }),
            }),
        ]),
        "bintie_ling": ([
            "name": NOR + CYN "镔铁令" NOR,
            "ids": ({ "bintie ling", "bintie", "ling" }),
            "weight": 1500,
            "damage": 10,
            "properties": ({
                ({ "unit", "支" }),
                ({ "value", 300 }),
                ({ "material", "steel" }),
            }),
        ]),
        "bishui_jian": ([
            "name": HIG "碧水剑" NOR,
            "ids": ({ "green sword", "jian" }),
            "weight": 7000,
            "damage": 20,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把通体晶莹剔透的剑，美丽之极，\n" }),
                ({ "value", 400 }),
                ({ "material", "crimsonsteel" }),
                ({ "wield_msg", "$N「唰」地一声抽出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插入腰间的剑鞘。\n" }),
            }),
        ]),
        "cangqiong_jian": ([
            "name": WHT "苍穹神剑" NOR,
            "ids": ({ "cangqiong jian", "cangqiong", "jian", "sword" }),
            "weight": 4000,
            "damage": 210,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n苍穹神剑乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "changjian": ([
            "name": "长剑",
            "ids": ({ "chang jian", "changjian", "jian", "sword", "s" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄普通的精钢剑，一般的剑客都配带此剑。\n" }),
                ({ "value", 500 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "changjian2": ([
            "name": "长剑",
            "ids": ({ "chang jian", "sword", "jian" }),
            "weight": 10000,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄普通的长剑。\n" }),
                ({ "value", 1000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "changjian4": ([
            "name": "长剑",
            "ids": ({ "sword", "changjian", "chang jian", "jian", "c" }),
            "weight": 7000,
            "damage": 25,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是一把看起相当普通的长剑，份量大约有十来斤左右。\n" }),
                ({ "value", 400 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」地一声抽出一把$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插入腰间的剑鞘。\n" }),
            }),
        ]),
        "chijian": ([
            "name": HIR "赤剑" NOR,
            "ids": ({ "chi jian", "jian", "sword", "chi", "chijian" }),
            "weight": 12000,
            "damage": 250,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIR "一柄四尺来长的长剑，整个剑身呈红色。\n" NOR }),
                ({ "value", 200000 }),
                ({ "rigidity", 8000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", HIR "$N" HIR "从背后抽出赤剑，顿时腾起一股凛冽的杀气。\n" NOR }),
                ({ "unwield_msg", HIR "$N" HIR "叹了口气，将赤剑插回背后。\n" NOR }),
            }),
        ]),
        "dongchang_jian": ([
            "name": "东厂铸剑",
            "ids": ({ "dongchang jian", "dongchang", "jian" }),
            "weight": 10000,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄官府卫兵特用的长剑，剑脊上铸有“东厂”二字。\n" }),
                ({ "value", 2000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "duan_yitian": ([
            "name": WHT "断了的倚天剑" NOR,
            "ids": ({ "duan jian", "sword" }),
            "weight": 10000,
            "damage": 1,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄断了的长剑\n" }),
                ({ "value", 0 }),
                ({ "rigidity", 8000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "duanjian": ([
            "name": "短剑",
            "ids": ({ "duanjian", "jian", "duan jian", "duan", "sword" }),
            "weight": 2000,
            "damage": 15,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄剑身短小的精钢剑，一般的剑客都配带此剑。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "duanjian2": ([
            "name": HIC "短剑" NOR,
            "ids": ({ "short sword", "sword", "jian" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄的短剑，据说剑里藏着一个极大秘密，几
百年来辗转相传，始终无人参详得出。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "fenghuang_qin": ([
            "name": HIM "凤凰琴" NOR,
            "ids": ({ "fenghuang qin", "fenghuang", "qin", "jian", "sword" }),
            "weight": 4000,
            "damage": 160,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n凤凰琴乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "ganggou": ([
            "name": "钢钩",
            "ids": ({ "ganggou", "gou" }),
            "weight": 5000,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄特殊的精钢剑，剑端带着一个倒钩。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回鞘中。\n" }),
            }),
        ]),
        "gangjian": ([
            "name": HIW "钢剑" NOR,
            "ids": ({ "gang jian", "sword", "jian" }),
            "weight": 10000,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄锋利的长剑。\n" }),
                ({ "value", 3000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "gangjian2": ([
            "name": "钢剑",
            "ids": ({ "jian", "sword" }),
            "weight": 6000,
            "damage": 30,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄精工制成的钢剑，这种剑在将领之间非常流行。\n" }),
                ({ "value", 400 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "ganjiang": ([
            "name": HIC "干将" NOR,
            "ids": ({ "ganjiang", "jian" }),
            "weight": 8000,
            "damage": 100,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这就是赫赫有名的干将,剑锋上隐隐透出一股清气,仔细凝望,只觉一股肃杀之气森热煌馍ⅰ�n" }),
                ({ "value", 20000 }),
                ({ "material", "steel" }),
                ({ "weapon_prop/personality", 8 }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中,顿时风沙飞扬,黑云罩日,漫天神鬼惊惧。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘,一下子风平浪静,晴空万里。\n" }),
            }),
        ]),
        "guanfu_jian": ([
            "name": "官府用剑",
            "ids": ({ "chang jian", "sword", "jian" }),
            "weight": 10000,
            "damage": 15,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄官府卫兵特用的长剑。\n" }),
                ({ "value", 2000 }),
                ({ "material", "gold" }),
            }),
        ]),
        "guilong": ([
            "name": HIY "金刚剑·鬼龙" NOR,
            "ids": ({ "gui long", "jingangjian", "jian", "sword" }),
            "weight": 4000,
            "damage": 200,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3700000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n金刚剑·鬼龙乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "gusong_jian": ([
            "name": MAG "古松残镢" NOR,
            "ids": ({ "gusong jian", "gusong", "jian", "sword" }),
            "weight": 4000,
            "damage": 90,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1000000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "guxing_jian": ([
            "name": HIW "孤星剑" NOR,
            "ids": ({ "guxing jian", "guxing", "jian", "sword" }),
            "weight": 4000,
            "damage": 50,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 300000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "hanyandai": ([
            "name": "旱烟袋",
            "ids": ({ "han yan", "yan" }),
            "weight": 500,
            "damage": 5,
            "properties": ({
                ({ "unit", "只" }),
                ({ "long", "这是一只用了好多年的铜烟袋。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一只$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰带中。\n" }),
            }),
        ]),
        "huanglong_jian": ([
            "name": HIY "黄龙剑" NOR,
            "ids": ({ "huanglong jian", "huanglong", "jian", "sword" }),
            "weight": 4000,
            "damage": 60,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 700000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "huoba": ([
            "name": "火把",
            "ids": ({ "huo ba" }),
            "weight": 10000,
            "damage": 5,
            "properties": ({
                ({ "unit", "支" }),
                ({ "value", 10000 }),
                ({ "material", "wood" }),
                ({ "long", "这是支火把。\n" }),
                ({ "wield_msg", "$N拿出一根$n，握在手中。\n" }),
                ({ "unequip_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "jindi": ([
            "name": HIY "金笛" NOR,
            "ids": ({ "jin di", "jin", "di" }),
            "weight": 10000,
            "damage": 30,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", HIY "一根由纯金打铸的笛子，在阳光下闪闪生辉。\n" NOR }),
                ({ "value", 25000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", HIY "$N" HIY "从腰间抽出一根金笛握在手中，轻轻玩弄。\n" NOR }),
                ({ "unwield_msg", HIY "$N" HIY "微微一笑，将手中的金笛插回腰间。\n" NOR }),
            }),
        ]),
        "jinwu_gou": ([
            "name": HIY "金蜈钩" NOR,
            "ids": ({ "jinwu gou", "gou", "jinwu" }),
            "weight": 5000,
            "damage": 200,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄金光闪闪的钩子，顶端好似一只蛇头。\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回鞘中。\n" }),
            }),
        ]),
        "liangtian_chi": ([
            "name": HIW "量天尺" NOR,
            "ids": ({ "liangtian chi", "liangtian", "chi", "jian", "sword" }),
            "weight": 4000,
            "damage": 140,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n量天尺乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "longhuang_jian": ([
            "name": MAG "龙凰紫珠" NOR,
            "ids": ({ "longhuang jian", "longhuang", "jian", "sword" }),
            "weight": 4000,
            "damage": 160,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3100000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n龙凰紫珠乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "longquan_jian": ([
            "name": CYN "龙泉剑" NOR,
            "ids": ({ "longquan sword", "longquan", "sword" }),
            "weight": 4000,
            "damage": 60,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是柄一看就知道是宝剑的利器。\n" }),
                ({ "value", 2400 }),
                ({ "material", "blacksteel" }),
                ({ "wield_msg", "只听见「飕」地一声，$N的手中已经多了一把寒光四射的宝剑----$n。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的剑鞘。\n" }),
            }),
        ]),
        "moye": ([
            "name": MAG "莫邪" NOR,
            "ids": ({ "moye", "jian" }),
            "weight": 8000,
            "damage": 100,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这就是赫赫有名的莫邪,剑锋上隐隐透出一股紫气,仔细凝望,只觉一股肃杀之气森然外散。\n" }),
                ({ "value", 20000 }),
                ({ "material", "steel" }),
                ({ "weapon_prop/personality", 8 }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中,顿时只听冤魂惨嚎,令人毛骨悚然。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘,一下子风平浪静,晴空万里。\n" }),
            }),
        ]),
        "mujian1": ([
            "name": "木剑",
            "ids": ({ "mu jian", "jian" }),
            "weight": 800,
            "damage": 1,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄用树枝削成的木剑。\n" }),
                ({ "value", 50 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "mujian2": ([
            "name": "木剑",
            "ids": ({ "woodjian", "jian" }),
            "weight": 500,
            "damage": 5,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄练功用的木剑，剑头是平的。\n" }),
                ({ "value", 100 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "mujian3": ([
            "name": "木剑",
            "ids": ({ "mu jian", "sword", "jian" }),
            "weight": 500,
            "damage": 3,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄木匠做的木剑，手工相当精细。\n" }),
                ({ "value", 50 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N从腰带里抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰带上。\n" }),
            }),
        ]),
        "nanhai_shenmu": ([
            "name": "南海神木",
            "ids": ({ "sea wood", "wood", "sword" }),
            "weight": 2000,
            "damage": 55,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根遍体发出青光的剑形木棍。\n" }),
                ({ "value", 2000 }),
                ({ "material", "wood" }),
                ({ "wield_msg", "$N从背后将南海神木拔出来，拿在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n重新插回背后。\n" }),
                ({ "stable", 90 }),
            }),
        ]),
        "panlong_jian": ([
            "name": YEL "盘龙七刹剑" NOR,
            "ids": ({ "panlong jian", "panlong", "jian", "sword" }),
            "weight": 4000,
            "damage": 130,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n盘龙七刹剑乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qilinjin1": ([
            "name": YEL "麒麟金·破" NOR,
            "ids": ({ "po", "qilinjin", "jian", "sword" }),
            "weight": 4000,
            "damage": 180,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3500000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n麒麟金·破乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qilinjin2": ([
            "name": YEL "麒麟金·曦" NOR,
            "ids": ({ "xi", "qilinjin", "jian", "sword" }),
            "weight": 4000,
            "damage": 175,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3500000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n麒麟金·曦乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qilinjin3": ([
            "name": YEL "麒麟金·鲸吞" NOR,
            "ids": ({ "jing tun", "qilinjin", "jian", "sword" }),
            "weight": 4000,
            "damage": 170,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3400000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n麒麟金·鲸吞乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "qingsha_jian": ([
            "name": HIB "青鲨嗜" NOR,
            "ids": ({ "qingsha jian", "qingsha", "jian", "sword" }),
            "weight": 4000,
            "damage": 120,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1600000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "qiyun_jian": ([
            "name": HIC "蹊云寒镢" NOR,
            "ids": ({ "qiyun jian", "qiyun", "jian", "sword" }),
            "weight": 4000,
            "damage": 95,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1200000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "ruanjian": ([
            "name": "软剑",
            "ids": ({ "ruanjian", "jian" }),
            "weight": 500,
            "damage": 35,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄用特殊材料制成的钢剑。\n" }),
                ({ "value", 150 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回剑鞘。\n" }),
            }),
        ]),
        "taia": ([
            "name": HIC "太阿" NOR,
            "ids": ({ "tai a", "taia", "jian", "sword" }),
            "weight": 4000,
            "damage": 190,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 3600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n太阿乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "taomu_jian": ([
            "name": "桃木剑",
            "ids": ({ "taomu jian", "jian" }),
            "weight": 1000,
            "damage": 10,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 100 }),
                ({ "material", "bamboo" }),
                ({ "long", "这是一把练习剑法用的桃木剑。\n" }),
                ({ "wield_msg", "$N拿出一把练剑用的$n，握在手中。\n" }),
                ({ "unequip_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "tianyue_jian": ([
            "name": HIC "天月寒镢" NOR,
            "ids": ({ "tianyue jian", "tianyue", "jian", "sword" }),
            "weight": 4000,
            "damage": 110,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 1500000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "tianzun_jian": ([
            "name": HIW "九仪天尊剑" NOR,
            "ids": ({ "tianzun jian", "tianzun", "jian", "sword" }),
            "weight": 4000,
            "damage": 230,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 4500000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n九仪天尊剑乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "tiedi": ([
            "name": HIB "铁笛" NOR,
            "ids": ({ "tie di" }),
            "weight": 500,
            "damage": 25,
            "properties": ({
                ({ "unit", "支" }),
                ({ "long", "一支黑铁做成的长笛，看上去坚忍异常。\n" }),
                ({ "value", 1000 }),
                ({ "material", "bamboo" }),
                ({ "wield_msg", "$N大袖一挥，手中已多了一支乌黑油光的铁笛。\n" }),
                ({ "unwield_msg", "$N手中铁笛一转，眨眼间铁笛已然不见影踪。\n" }),
            }),
        ]),
        "tiegan": ([
            "name": "细铁杆",
            "ids": ({ "tie-gan" }),
            "weight": 8000,
            "damage": 10,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根又细又张的铁杆。\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N拿出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n放下。\n" }),
            }),
        ]),
        "wudu_jian": ([
            "name": HIR "五毒神剪" NOR,
            "ids": ({ "wudu shenjian", "jian", "shenjian" }),
            "weight": 5000,
            "damage": 70,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄奇门兵器，好似一只大剪刀。\n" }),
                ({ "value", 10000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N「唰」的一声掏出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n挂在腰间。\n" }),
            }),
        ]),
        "wugou_jian": ([
            "name": HIC "吴钩剑" NOR,
            "ids": ({ "wugou jian", "wugou", "jian", "sword" }),
            "weight": 4000,
            "damage": 60,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 400000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "wuyang_jian": ([
            "name": YEL "吴阳剑" NOR,
            "ids": ({ "wuyang jian", "wuyang", "jian", "sword" }),
            "weight": 4000,
            "damage": 80,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 900000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "xiuhua_zhen": ([
            "name": "绣花针",
            "ids": ({ "xiuhua zhen", "zhen", "needle" }),
            "weight": 5,
            "damage": 10,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根精钢细磨的绣花针，是绣花用的工具。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N用拇指和食指从鬓间拈出一根$n。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回鬓间。\n" }),
            }),
        ]),
        "xiuhua_zhen2": ([
            "name": "绣花针",
            "ids": ({ "xiuhua zhen", "zhen", "needle" }),
            "weight": 5,
            "damage": 10,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根精钢细磨的绣花针，是绣花用的绝佳工具。\n" }),
                ({ "value", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N用拇指和食指从鬓间拈出一根$n。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回鬓间。\n" }),
            }),
        ]),
        "xuanchi_jian": ([
            "name": WHT "玄蚩神剑" NOR,
            "ids": ({ "chiyou jian", "sword", "jian" }),
            "weight": 20000,
            "damage": 200,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "一柄玄铁铸造的长剑，剑柄上雕有蚩尤的头像。\n" }),
                ({ "value", 100000 }),
                ({ "material", "gold" }),
                ({ "wield_msg", HIR "$N" HIR "抽出玄蚩神剑挥舞了个剑花，只感到一阵"
                    NOR + HIW "寒气" NOR + HIR "扑面而来。\n" NOR }),
            }),
        ]),
        "xuanyuan_jian": ([
            "name": CYN "轩辕神剑" NOR,
            "ids": ({ "xuanyuan jian", "xuanyuan", "jian", "sword" }),
            "weight": 4000,
            "damage": 220,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 4000000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n轩辕神剑乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "yanyang_chi": ([
            "name": HIM "九天艳阳尺" NOR,
            "ids": ({ "yanyang chi", "yanyang", "chi", "jian", "sword" }),
            "weight": 4000,
            "damage": 155,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 2800000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n九天艳阳尺乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "yitian_jian": ([
            "name": NOR + WHT "倚天剑" NOR,
            "ids": ({ "yitian jian", "yitian", "jian", "sword" }),
            "weight": 5000,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIY "这便与天下至尊的屠龙宝刀并称的倚天剑。\n" NOR }),
                ({ "value", 500 }),
                ({ "material", "wood" }),
                ({ "wield_msg", HIM "$N" HIM "「唰」的抽出$n" HIM "，顿时闻"
                    "到一股奇异的香味。\n仔细一看，原来这柄倚天"
                    "剑竟是木头制成的。\n" NOR }),
            }),
        ]),
        "youlong_jian": ([
            "name": "游龙剑",
            "ids": ({ "youlong sword", "youlong", "sword" }),
            "weight": 8000,
            "damage": 80,
            "properties": ({
                ({ "unit", "把" }),
                ({ "long", "这是把看起来很普通的长剑，但仔细一看，剑身上有几条细纹闪烁不定。\n" }),
                ({ "value", 2400 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "只听见「飕」地一声，$N的手中已经多了一把寒光四射的宝剑----$n。\n" }),
                ({ "unequip_msg", "$N将手中的$n插入腰间的剑鞘。\n" }),
                ({ "stable", 75 }),
            }),
        ]),
        "yujian": ([
            "name": HIW "玉剑" NOR,
            "ids": ({ "yu jian", "yu", "jian", "sword" }),
            "weight": 500,
            "damage": 10,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIW "一柄用白玉做成的长剑，相当的精美。\n" NOR }),
                ({ "value", 5000 }),
                ({ "material", "jade" }),
            }),
        ]),
        "zhujian1": ([
            "name": "竹剑",
            "ids": ({ "zhujian", "jian", "sword" }),
            "weight": 1000,
            "damage": 3,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 100 }),
                ({ "material", "bamboo" }),
                ({ "long", "这是一把练习剑法用的竹剑。\n" }),
                ({ "wield_msg", "$N拿出一把$n，握在手中。\n" }),
                ({ "unequip_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "zhujian2": ([
            "name": "竹剑",
            "ids": ({ "zhu jian", "jian", "sword" }),
            "weight": 1000,
            "damage": 10,
            "properties": ({
                ({ "unit", "把" }),
                ({ "value", 100 }),
                ({ "material", "bamboo" }),
                ({ "long", "这是一柄三尺来长，精工制成的青竹剑，虽不致命，却可伤人。\n" }),
                ({ "wield_msg", "$N拿出一把$n，握在手中。\n" }),
                ({ "unequip_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
    ]);
}
