// 普通暗器的蓝图属性；规范 ID 自然排序，数量由每个对象独立初始化。
private mapping throwing_definitions() {
    return ([
        "bilin_zhen": ([
            "name": HIG "碧磷针" NOR,
            "ids": ({ "bilin zhen", "zhen" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "枚" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIG "碧磷针是星宿派使用的，暗器，常常"
                    "淬毒。针长寸许，发出诡异的光。\n" NOR }),
                ({ "wield_msg", HIC "$N迅速地从身上摸出一些碧磷针，捏"
                    "在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的碧磷针一抖就不见了"
                    "。\n" NOR }),
            }),
        ]),
        "duandao": ([
            "name": "短刀",
            "ids": ({ "short blade", "dao" }),
            "amount": 18,
            "damage": 25,
            "properties": ({
                ({ "value", 0 }),
                ({ "base_unit", "柄" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "unit", "把" }),
                ({ "long", "这是一捆飞刀。\n" }),
                ({ "value", 1000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "dujili": ([
            "name": HIB "毒蒺藜" NOR,
            "ids": ({ "du jili", "jili" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "枚" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIG "毒蒺藜是淬毒暗器，寸许大小，发出诡异的光。\n" NOR }),
                ({ "wield_msg", HIC "$N迅速地从身上摸出一些毒蒺藜，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的毒蒺藜一抖就不见了。\n" NOR }),
            }),
        ]),
        "eluanshi": ([
            "name": HIC "鹅卵石" NOR,
            "ids": ({ "eluan shi", "shi" }),
            "amount": 10,
            "damage": 1,
            "properties": ({
                ({ "unit", "些" }),
                ({ "long", "这是一粒平平常常的鹅卵石。\n" }),
                ({ "base_unit", "粒" }),
                ({ "base_weight", 300 }),
                ({ "value", 0 }),
                ({ "material", "stone" }),
                ({ "wield_msg", "$N掏出一粒$n准备战斗。\n" }),
                ({ "unwield_msg", "$N放下手中的$n。\n" }),
            }),
        ]),
        "feidao": ([
            "name": "小飞刀",
            "ids": ({ "xiao feidao", "feidao" }),
            "amount": 5,
            "damage": 15,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 500 }),
                ({ "base_unit", "把" }),
                ({ "base_value", 100 }),
                ({ "base_weight", 1000 }),
                ({ "material", "steel" }),
                ({ "long", "一把雪亮的飞刀。\n" }),
            }),
        ]),
        "feihuangshi": ([
            "name": "飞璜石",
            "ids": ({ "shi" }),
            "amount": 20,
            "damage": 20,
            "properties": ({
                ({ "long", "飞璜石是一种十分常见的暗器。\n" }),
                ({ "unit", "些" }),
                ({ "base_unit", "块" }),
                ({ "base_weight", 50 }),
                ({ "value", 50 }),
            }),
        ]),
        "feihuangshi2": ([
            "name": "飞蝗石",
            "ids": ({ "feihuang shi", "shi" }),
            "amount": 20,
            "damage": 25,
            "properties": ({
                ({ "long", "仔细挑选的鹅卵石，大小一致，个个都滴溜溜圆。\n" }),
                ({ "unit", "把" }),
                ({ "value", 0 }),
                ({ "base_unit", "个" }),
                ({ "base_weight", 1 }),
                ({ "base_value", 0 }),
                ({ "damage", 5 }),
                ({ "material", "stone" }),
                ({ "wield_msg", HIC "$N迅速地从暗器袋中掏出一些飞蝗石，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的飞蝗石尽数放回暗器袋中。\n" NOR }),
            }),
        ]),
        "furong_zhen": ([
            "name": HIY "芙蓉金针" NOR,
            "ids": ({ "furong jinzhen", "furong", "jinzhen", "zhen" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 200 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIY "这是一些细长的金针，长约寸许。\n" NOR }),
            }),
        ]),
        "heixue_zhen": ([
            "name": WHT "黑血神针" NOR,
            "ids": ({ "heixue shenzhen", "heixue", "shenzhen", "zhen" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 200 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", WHT "这是一些暗灰色的细长金针，长约寸许。\n" NOR }),
            }),
        ]),
        "huaban": ([
            "name": HIR "花瓣" NOR,
            "ids": ({ "flower leaf", "hua ban", "ban" }),
            "amount": 50,
            "damage": 2,
            "properties": ({
                ({ "long", "新鲜的玫瑰花的花瓣，上面还挂着晶莹的露珠。\n" }),
                ({ "unit", "把" }),
                ({ "value", 0 }),
                ({ "base_unit", "片" }),
                ({ "base_weight", 1 }),
                ({ "base_value", 0 }),
                ({ "material", "wood" }),
                ({ "damage", 2 }),
                ({ "wield_msg", HIC "$N迅速地从暗器袋中掏出一些玫瑰花瓣，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的玫瑰花瓣尽数放回暗器袋中。\n" NOR }),
            }),
        ]),
        "jinbiao": ([
            "name": HIY "金镖" NOR,
            "ids": ({ "jin biao", "jin", "biao" }),
            "amount": 10,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 2000 }),
                ({ "base_unit", "支" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 4000 }),
                ({ "material", "iron" }),
            }),
        ]),
        "jinbiao2": ([
            "name": HIY "金镖" NOR,
            "ids": ({ "jinbiao", "biao" }),
            "amount": 1,
            "damage": 80,
            "properties": ({
                ({ "long", "这是一把用纯金打造成的飞镖，价格昂贵，闪闪发光。\n" }),
                ({ "unit", "些" }),
                ({ "base_value", 200 }),
                ({ "material", "gold" }),
                ({ "base_unit", "枚" }),
                ({ "base_weight", 50 }),
            }),
        ]),
        "jinshe_zhui": ([
            "name": YEL "金蛇锥" NOR,
            "ids": ({ "jinshe zhui", "zhui" }),
            "amount": 15,
            "damage": 35,
            "properties": ({
                ({ "long", "金蛇锥是黄金所铸，灿烂生光。长约二寸八分，打成昂首吐舌的蛇
形，蛇舌尖端分成双叉，每一叉都是一个倒刺。\n" }),
                ({ "unit", "把" }),
                ({ "value", 0 }),
                ({ "base_unit", "枚" }),
                ({ "base_weight", 10 }),
                ({ "base_value", 0 }),
            }),
        ]),
        "lanwu_zhen": ([
            "name": HIR "斓蜈金针" NOR,
            "ids": ({ "lanwu jinzhen", "lanwu", "jinzhen", "zhen" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 200 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIR "这是一些血红色的细长金针，长约寸许。\n" NOR }),
            }),
        ]),
        "leiting_zhen": ([
            "name": HIR "雷霆神针" NOR,
            "ids": ({ "leiting shenzhen", "zhen" }),
            "amount": 50,
            "damage": 120,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 250000 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 5000 }),
                ({ "material", "iron" }),
            }),
        ]),
        "lianxin_dan": ([
            "name": HIG "炼心弹" NOR,
            "ids": ({ "lianxin dan", "dan" }),
            "amount": 50,
            "damage": 10,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "颗" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIG "炼心弹是星宿派淬毒暗器，针长寸许，发出诡异的光。\n" NOR }),
                ({ "wield_msg", HIC "$N迅速地从鹿皮袋中摸出一些炼心弹，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的炼心弹收回鹿皮袋中。\n" NOR }),
            }),
        ]),
        "longxiang_zhen": ([
            "name": HIY "龙翔神针" NOR,
            "ids": ({ "longxiang shenzhen", "zhen" }),
            "amount": 50,
            "damage": 100,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 200000 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 4000 }),
                ({ "material", "iron" }),
            }),
        ]),
        "qizi": ([
            "name": CYN "棋子" NOR,
            "ids": ({ "qi zi", "qi", "zi" }),
            "amount": 40,
            "damage": 10,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "颗" }),
                ({ "base_weight", 1 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
            }),
        ]),
        "shizi": ([
            "name": WHT "石子" NOR,
            "ids": ({ "shi zi", "shi", "zi" }),
            "amount": 10,
            "damage": 2,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "颗" }),
                ({ "base_weight", 100 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", "一颗不同的小石子。\n" }),
            }),
        ]),
        "taohua_ban": ([
            "name": HIM "桃花瓣" NOR,
            "ids": ({ "flower leaf", "hua ban", "ban" }),
            "amount": 50,
            "damage": 2,
            "properties": ({
                ({ "long", HIM "新鲜的桃花花瓣，上面还挂着晶莹的露珠。\n" NOR }),
                ({ "unit", "把" }),
                ({ "value", 0 }),
                ({ "base_unit", "片" }),
                ({ "base_weight", 1 }),
                ({ "base_value", 0 }),
                ({ "material", "wood" }),
                ({ "damage", 2 }),
            }),
        ]),
        "tianqiong_zhen": ([
            "name": HIW "天穹神针" NOR,
            "ids": ({ "tianqiong shenzhen", "zhen" }),
            "amount": 50,
            "damage": 70,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 100000 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 2000 }),
                ({ "material", "iron" }),
            }),
        ]),
        "tiedan": ([
            "name": HIW "铁胆" NOR,
            "ids": ({ "tiedan", "dan" }),
            "amount": 50,
            "damage": 30,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "枚" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIG "一些溜圆的铁胆，是一种凶猛的暗器。\n" NOR }),
                ({ "wield_msg", HIC "$N迅速地从身上摸出一些铁胆，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的铁胆一抖就不见了。\n" NOR }),
            }),
        ]),
        "tielianzi": ([
            "name": HIC "铁莲子" NOR,
            "ids": ({ "tie lianzi", "lianzi", "tie" }),
            "amount": 50,
            "damage": 25,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 0 }),
                ({ "base_unit", "颗" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIW "铁莲子是一种以量取胜的暗器，沉甸甸的。\n" NOR }),
                ({ "wield_msg", HIC "$N迅速地从暗器袋中掏出一些铁莲子，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的铁莲子尽数放回暗器袋中。\n" NOR }),
            }),
        ]),
        "tielianzi2": ([
            "name": "铁莲子",
            "ids": ({ "tie lianzi", "lianzi", "zi" }),
            "amount": 30,
            "damage": 15,
            "properties": ({
                ({ "long", "精铁打制的莲子状暗器。\n" }),
                ({ "unit", "把" }),
                ({ "base_unit", "粒" }),
                ({ "base_weight", 1 }),
                ({ "base_value", 1 }),
                ({ "material", "iron" }),
                ({ "wield_msg", HIC "$N迅速地从暗器袋中掏出"
                    "一些铁莲子，捏在手中就待发出！\n" NOR }),
                ({ "unwield_msg", HIC "$N将手里剩下的铁莲子尽数放回暗器袋中。\n" NOR }),
            }),
        ]),
        "xianhe_zhen": ([
            "name": HIW "仙鹤神针" NOR,
            "ids": ({ "xianhe shenzhen", "zhen" }),
            "amount": 50,
            "damage": 50,
            "properties": ({
                ({ "unit", "些" }),
                ({ "value", 50000 }),
                ({ "base_unit", "根" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 1000 }),
                ({ "material", "iron" }),
            }),
        ]),
        "xiaoli_feidao": ([
            "name": HIW "小李飞刀" NOR,
            "ids": ({ "xiaoli feidao", "feidao" }),
            "amount": 1,
            "damage": 300,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "value", 6000 }),
                ({ "base_unit", "柄" }),
                ({ "base_weight", 300 }),
                ({ "base_value", 0 }),
                ({ "material", "iron" }),
                ({ "long", HIW "一柄看似普通的飞刀，刀柄上刻了个小小的“李”字。\n" NOR }),
                ({ "wield_msg", HIW "$N" HIW "手臂微微一抖，手中已多了柄明晃晃的飞刀。\n" NOR }),
                ({ "unwield_msg", HIW "$N" HIW "手臂微微一抖，手中的飞刀便已消逝不见。\n" NOR }),
            }),
        ]),
    ]);
}
