// 普通鞭类物品的蓝图属性；规范 ID 自然排序，伤害与标志由 init_whip 初始化。
private mapping whip_definitions() {
    return ([
        "changbian": ([
            "name": "长鞭",
            "ids": ({ "changbian", "bian" }),
            "weight": 500,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄普通的长鞭，由水牛精工编织而成。\n" }),
                ({ "value", 100 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "changbian2": ([
            "name": "长鞭",
            "ids": ({ "changbian", "bian" }),
            "weight": 500,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄普通的长鞭，由水牛精工编织而成。\n" }),
                ({ "value", 100 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "chanhun_si": ([
            "name": HIW "缠魂丝" NOR,
            "ids": ({ "chanhun si", "si", "chanhun", "whip" }),
            "weight": 4000,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 230000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "diaogan": ([
            "name": "钓杆",
            "ids": ({ "diao gan", "diao", "gan" }),
            "weight": 5000,
            "damage": 30,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根细长的铁杆，猛然一看不过是根普通钓鱼用的吊杆。\n" }),
                ({ "value", 1500 }),
                ({ "rigidity", 100 }),
                ({ "material", "steel" }),
                ({ "wield_msg", "$N抽出一根$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n插回腰间。\n" }),
            }),
        ]),
        "fuchen": ([
            "name": "拂尘",
            "ids": ({ "fu chen", "fu", "chen" }),
            "weight": 500,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄普通的拂尘。\n" }),
                ({ "value", 100 }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "fuchen2": ([
            "name": "拂尘",
            "ids": ({ "fuchen" }),
            "weight": 300,
            "damage": 20,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄拂尘，做工精细，是很阴毒的兵器。\n" }),
                ({ "value", 30 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声从颈中抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n别回颈中。\n" }),
            }),
        ]),
        "fuchen3": ([
            "name": "拂尘",
            "ids": ({ "fuchen" }),
            "weight": 300,
            "damage": 50,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄拂尘，做工精细，是很阴毒的兵器。\n" }),
                ({ "value", 30 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声从颈中抽出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n别回颈中。\n" }),
            }),
        ]),
        "heilong_bian": ([
            "name": "黑龙鞭",
            "ids": ({ "heilong bian", "bian" }),
            "weight": 500,
            "damage": 35,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄墨黑长鞭，坚韧无比。\n" }),
                ({ "value", 1000 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "heisuo": ([
            "name": "黑索",
            "ids": ({ "black whip", "hei suo", "suo", "whip" }),
            "weight": 800,
            "damage": 120,
            "properties": ({
                ({ "unit", "根" }),
                ({ "long", "这是一根漆黑的长鞭，毫不起眼，但是入手沉重，且\n"
                    "不失柔韧，实在是千锤百炼之物。\n" }),
                ({ "no_sell", "这是啥破玩艺，上吊用的？\n" }),
                ({ "value", 50000 }),
                ({ "material", "steel" }),
                ({ "wield_msg", BLK "$N" BLK "一伸手，悄无声息的将$n握在手中。\n" NOR }),
                ({ "unwield_msg", WHT "$N" WHT "将手中的$n卷起收好。\n" NOR }),
                ({ "stable", 70 }),
            }),
        ]),
        "huntun_suo": ([
            "name": WHT "馄饨灵索" NOR,
            "ids": ({ "huntun suo", "huntun", "suo", "whip" }),
            "weight": 4000,
            "damage": 90,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1200000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "jiujiebian": ([
            "name": "九节鞭",
            "ids": ({ "jiujie bian", "bian" }),
            "weight": 500,
            "damage": 25,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一条九节鞭，由精钢铸就而成。\n" }),
                ({ "value", 100 }),
                ({ "material", "steal" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "liehuo_bian": ([
            "name": HIR "烈火神鞭" NOR,
            "ids": ({ "liehuo bian", "bian", "liehuo", "whip" }),
            "weight": 4000,
            "damage": 60,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 420000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "liuxing_chui": ([
            "name": HIY "流星锤" NOR,
            "ids": ({ "liuxing chui", "liuxing", "chui" }),
            "weight": 4500,
            "damage": 40,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", HIY "一柄金光闪闪的流星锤。\n" NOR }),
                ({ "value", 2000 }),
                ({ "material", "leather" }),
            }),
        ]),
        "panlong_suo": ([
            "name": HIR "盘龙索" NOR,
            "ids": ({ "panlong suo", "suo", "panlong", "whip" }),
            "weight": 4000,
            "damage": 55,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 360000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "pibian": ([
            "name": "皮鞭",
            "ids": ({ "pi bian", "pibian", "bian", "whip" }),
            "weight": 1000,
            "damage": 15,
            "properties": ({
                ({ "long", "一条长长的皮鞭．\n" }),
                ({ "unit", "条" }),
                ({ "value", 500 }),
            }),
        ]),
        "qilin_bian": ([
            "name": RED "麒麟鞭" NOR,
            "ids": ({ "qilin bian", "qilin", "bian", "whip" }),
            "weight": 4000,
            "damage": 70,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 650000 }),
                ({ "material", "steel" }),
            }),
        ]),
        "shebian": ([
            "name": "蛇鞭",
            "ids": ({ "shebian", "bian" }),
            "weight": 700,
            "damage": 30,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄蛇皮长鞭。\n" }),
                ({ "value", 300 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n卷回腰间。\n" }),
            }),
        ]),
        "shenjiao_si1": ([
            "name": HIW "神蛟丝·天残" NOR,
            "ids": ({ "tian can", "shenjiaosi", "suo", "whip" }),
            "weight": 4000,
            "damage": 140,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n神蛟丝·天残乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "shenjiao_si2": ([
            "name": HIW "神蛟丝·天缺" NOR,
            "ids": ({ "tian que", "shenjiaosi", "suo", "whip" }),
            "weight": 4000,
            "damage": 160,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 2300000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n神蛟丝·天缺乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "shenjiao_si3": ([
            "name": HIY "神蛟丝·噬月" NOR,
            "ids": ({ "shi yue", "shenjiaosi", "suo", "whip" }),
            "weight": 4000,
            "damage": 180,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 3200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n神蛟丝·噬月乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "shenjiao_si4": ([
            "name": HIR "神蛟丝·吞日" NOR,
            "ids": ({ "tun ri", "shenjiaosi", "suo", "whip" }),
            "weight": 4000,
            "damage": 200,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 3600000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n神蛟丝·吞日乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "suolian": ([
            "name": HIW "锁链" NOR,
            "ids": ({ "suo lian", "suo", "lian" }),
            "weight": 300,
            "damage": 50,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 30 }),
                ({ "material", "leather" }),
            }),
        ]),
        "tiebian": ([
            "name": "铁鞭",
            "ids": ({ "changbian", "bian" }),
            "weight": 500,
            "damage": 40,
            "properties": ({
                ({ "unit", "柄" }),
                ({ "long", "这是一柄粗大的铁鞭，总有三十来斤重。\n" }),
                ({ "value", 100 }),
                ({ "material", "leather" }),
                ({ "wield_msg", "$N「唰」的一声抖出一柄$n握在手中。\n" }),
                ({ "unwield_msg", "$N将手中的$n别回腰间。\n" }),
            }),
        ]),
        "wulong_si": ([
            "name": CYN "乌龙神蛟丝" NOR,
            "ids": ({ "wulong si", "shenjiaosi", "si", "whip" }),
            "weight": 4000,
            "damage": 220,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 3900000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n乌龙神蛟丝乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
        "xuanbing_suo": ([
            "name": HIW "玄冰索" NOR,
            "ids": ({ "xuanbing suo", "xuanbing", "suo", "whip" }),
            "weight": 4000,
            "damage": 110,
            "properties": ({
                ({ "unit", "根" }),
                ({ "value", 1200000 }),
                ({ "material", "steel" }),
                ({ "long", HIW "\n玄冰索乃九穹七狱神兵之一。\n" NOR }),
                ({ "wield_msg", HIR "$N轻轻抖出$n" HIR "，刹时雷声轰鸣，一股杀气直慑九霄。\n" }),
            }),
        ]),
    ]);
}
